"""
CAMA-D Stage 3: CGM-GRPO (Culture-Guided Mixed-Policy GRPO)

Core innovation over train_grpo_v3.py:
  - Guardian as advantage augmentation signal (NOT in RLOO baseline)
  - Three-factor w_culture: 0.6*(1-hit_rate) + 0.3*rarity + 0.1*(1-affinity)
  - No importance sampling needed (Guardian only contributes a scalar bonus)
  - Quality gate: bonus zeroes out when Guardian answers wrong

Performance optimizations over v3:
  - Batch Generate: all prompts in one model.generate() call (50-70% faster generate)
  - Batch LogProb: vectorized forward pass for ref/policy log-probs (80%+ faster)
  - Mini-batch backward: accumulate gradients over small groups (50-60% faster)

Architecture (LoRA, no DeepSpeed):
  - Policy: base model + SFT-LoRA merged + new GRPO-LoRA (trainable) on cuda:0
  - Reference: same model with adapter disabled (zero extra memory)
  - PRM: loaded on cuda:1 for parallel scoring (frozen, eval mode)

Hardware requirement: 2x vGPU-48GB (policy on cuda:0, PRM on cuda:1)

Usage:
    # Quick test with 10 samples
    python Cul/grpo/train_grpo_mixed_policy.py \\
        --model_name     qwen \\
        --sft_adapter    /path/to/camad_sft_qwen/best \\
        --data_pkl       /path/to/normad_splits.pkl \\
        --prm_path       /path/to/camad_prm/best \\
        --guardian_data  /path/to/normad_hf_cac_inference.jsonl \\
        --output_dir     /path/to/models/camad_cgm_grpo \\
        --max_train_samples 10 \\
        --max_rounds     3 \\
        --n_samples      5

    # Full training with CGM-GRPO
    python Cul/grpo/train_grpo_mixed_policy.py \\
        --model_name     qwen \\
        --sft_adapter    /path/to/camad_sft_qwen/best \\
        --data_pkl       /path/to/normad_splits.pkl \\
        --prm_path       /path/to/camad_prm/best \\
        --guardian_data  /path/to/normad_hf_cac_inference.jsonl \\
        --output_dir     /path/to/models/camad_cgm_grpo \\
        --guardian_lambda 0.5 \\
        --w_culture_mode hit_rarity \\
        --n_samples      5 \\
        --max_rounds     20 \\
        --batches_per_round 130

    The --data_pkl file should be generated by split_data.py.
    The --guardian_data is the HF-CAC inference JSONL from Stage 0.
"""

import re
import os
import json
import yaml
import pickle
import argparse
import sys
from contextlib import nullcontext
from pathlib import Path
from collections import defaultdict

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import LoraConfig, get_peft_model, PeftModel, TaskType

# Import step splitting utility
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from step_label.split_steps import split_reasoning_into_steps


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MODEL_ALIASES = {
    "llama": "/root/autodl-tmp/base/Meta-Llama-3.1-8B-Instruct",
    "qwen":  "/root/autodl-tmp/base/Qwen2.5-7B-Instruct",
}

MAX_GEN_LEN = 128
MAX_PROMPT_LEN = 512
KL_COEF = 0.05
DEFAULT_ALPHA = 0.6


# ---------------------------------------------------------------------------
# Guardian Data Loading
# ---------------------------------------------------------------------------

def load_guardian_index(guardian_jsonl_path: str) -> dict:
    """
    Load HF-CAC inference JSONL and build lookup index for Guardian responses.

    Returns:
        Dict mapping (country_lower, query_prefix_lower) -> {
            "guardian_response": str,
            "guardian_answer": str,
            "guardian_name": str,
        }
    """
    index = {}
    count = 0
    with open(guardian_jsonl_path, "r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            obj = json.loads(line)
            query = obj.get("query", "").strip()
            country = obj.get("country", "").strip()
            response = obj.get("response", "")
            guardian_idx = obj.get("guardian_idx", -1)
            guardian_failed = obj.get("guardian_failed", True)

            if guardian_failed or guardian_idx < 0:
                continue

            guardian_text = _extract_guardian_text(response)
            if not guardian_text:
                continue

            guardian_answer = _extract_guardian_answer(guardian_text)
            key = (country.lower(), query[:200].lower())
            index[key] = {
                "guardian_response": guardian_text,
                "guardian_answer": guardian_answer,
                "guardian_name": obj.get("guardian_name", ""),
            }
            count += 1

    print(f"  [Guardian] Loaded {count} Guardian responses from {guardian_jsonl_path}")
    return index


def _extract_guardian_text(formatted_response: str) -> str:
    """Extract Guardian's text from formatted multi-agent response."""
    pattern = r'===== Solution \d+ \[GUARDIAN\] =====\n(.*?)(?=\n===== Solution|\Z)'
    match = re.search(pattern, formatted_response, re.DOTALL)
    if match:
        return match.group(1).strip()
    return ""


def _extract_guardian_answer(text: str) -> str:
    """Extract answer digit from Guardian response text."""
    first_line = text.split("\n")[0].strip()
    m = re.match(r'^([1-4])\b', first_line)
    if m:
        return m.group(1)
    m = re.search(r"Answer\s*:\s*([1-4])", text, re.IGNORECASE)
    if m:
        return m.group(1)
    digits = re.findall(r"\b([1-4])\b", text)
    return digits[0] if digits else None


# ---------------------------------------------------------------------------
# Cultural Difficulty: w_culture maps and computation
# ---------------------------------------------------------------------------

def load_affinity_matrix(config_path: str) -> tuple:
    """
    Load cultural affinity matrix and region keywords from hf_cac_config.yaml.

    Returns:
        (affinity_matrix: list[list[float]], country_to_circle: dict[str, int])
    """
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)

    matrix = config["cultural_affinity_matrix"]
    country_to_circle = {}

    for idx, role in enumerate(config["culture_roles"]):
        for keyword in role.get("region_keywords", []):
            country_to_circle[keyword.lower().strip()] = idx

    return matrix, country_to_circle


def build_culture_maps(train_data: list, affinity_config: str = None) -> tuple:
    """
    Build rarity_map and affinity_map from training data.

    Returns:
        (rarity_map: dict[str, float], affinity_map: dict[str, float])
        Maps country_name_lower -> value.
    """
    rarity_map = {}
    affinity_map = {}

    if not affinity_config or not os.path.exists(affinity_config):
        return rarity_map, affinity_map

    matrix, country_to_circle = load_affinity_matrix(affinity_config)

    # Compute rarity per circle
    circle_counts = defaultdict(int)
    total = 0
    for sample in train_data:
        country = sample.get("country", "").lower().strip()
        circle_idx = country_to_circle.get(country, -1)
        if circle_idx >= 0:
            circle_counts[circle_idx] += 1
        total += 1

    circle_rarity = {}
    for idx in range(len(matrix)):
        freq = circle_counts[idx] / max(total, 1)
        circle_rarity[idx] = 1.0 - freq

    # Compute isolation (1 - avg_affinity) per circle
    circle_isolation = {}
    n = len(matrix)
    for i in range(n):
        off_diag = [matrix[i][j] for j in range(n) if j != i]
        avg_aff = sum(off_diag) / max(len(off_diag), 1)
        circle_isolation[i] = 1.0 - avg_aff

    # Build per-country maps
    for country_name, circle_idx in country_to_circle.items():
        rarity_map[country_name] = circle_rarity.get(circle_idx, 0.5)
        affinity_map[country_name] = circle_isolation.get(circle_idx, 0.5)

    return rarity_map, affinity_map


# ---------------------------------------------------------------------------
# CGM-GRPO: Guardian Advantage Augmentation
# ---------------------------------------------------------------------------

def apply_cgm_guardian_bonus(
    advantages: torch.Tensor,
    rewards: torch.Tensor,
    queries: list,
    countries: list,
    golds: list,
    r_outcomes: list,
    guardian_index: dict,
    guardian_lambda: float,
    w_culture_mode: str,
    rarity_map: dict,
    affinity_map: dict,
    n_samples: int,
    hit_threshold: float = 0.8,
) -> tuple:
    """
    Apply CGM-GRPO Guardian advantage augmentation in-place.

    Formula: bonus = lambda * w_culture * S_guardian
    Where:
        S_guardian = R_outcome_guardian * (R_guardian - R_on_bar_full)
        w_culture depends on mode (hit_only / hit_rarity / full)

    The bonus is UNIFORM for all on-policy rollouts of the same prompt
    (shifts the entire advantage distribution up/down).

    Returns:
        (modified_advantages, stats_dict)
    """
    n_prompts = advantages.size(0)
    stats = {
        "guardian_found": 0,
        "guardian_correct": 0,
        "n_applied": 0,
        "mean_w_culture": 0.0,
        "mean_s_guardian": 0.0,
    }

    for pi in range(n_prompts):
        country = countries[pi]
        query = queries[pi]
        gold = str(golds[pi]).strip()

        # Look up Guardian data
        key = (country.lower().strip(), query[:200].lower().strip())
        guardian_data = guardian_index.get(key, None)
        if guardian_data is None:
            continue
        stats["guardian_found"] += 1

        # Quality gate: Guardian must have answered correctly
        guardian_answer = guardian_data["guardian_answer"]
        if guardian_answer is None:
            continue
        r_outcome_guardian = 1.0 if guardian_answer == gold else 0.0
        if r_outcome_guardian < 0.5:
            continue
        stats["guardian_correct"] += 1

        # R_on_bar_full = mean of on-policy R_total for this prompt
        r_on_bar_full = rewards[pi].mean().item()

        # S_guardian = R_outcome_guardian * (R_guardian - R_on_bar_full)
        # R_guardian = 1.0 (since Guardian answered correctly)
        r_guardian = 1.0
        s_guardian = r_outcome_guardian * (r_guardian - r_on_bar_full)

        if abs(s_guardian) < 1e-8:
            continue

        # hit_rate for this prompt (fraction of on-policy correct)
        hit_rate = 0.0
        for si in range(n_samples):
            idx = pi * n_samples + si
            if idx < len(r_outcomes) and r_outcomes[idx] > 0.5:
                hit_rate += 1.0
        hit_rate /= n_samples

        # Compute w_culture based on mode
        country_key = country.lower().strip()
        if w_culture_mode == "hit_only":
            w_val = 1.0 - hit_rate
        elif w_culture_mode == "hit_rarity":
            rarity = rarity_map.get(country_key, 0.5)
            w_val = 0.67 * (1.0 - hit_rate) + 0.33 * rarity
        else:  # "full"
            rarity = rarity_map.get(country_key, 0.5)
            isolation = affinity_map.get(country_key, 0.5)
            w_val = 0.6 * (1.0 - hit_rate) + 0.3 * rarity + 0.1 * isolation

        w_val = max(0.0, min(1.0, w_val))

        # Necessity gate: if hit_rate >= threshold, skip guidance
        if hit_rate >= hit_threshold:
            w_val = 0.0

        # Apply uniform bonus to all samples of this prompt
        bonus = guardian_lambda * w_val * s_guardian
        advantages[pi] += bonus

        stats["mean_w_culture"] += w_val
        stats["mean_s_guardian"] += s_guardian
        stats["n_applied"] += 1

    # Normalize stats
    if stats["n_applied"] > 0:
        stats["mean_w_culture"] /= stats["n_applied"]
        stats["mean_s_guardian"] /= stats["n_applied"]

    return advantages, stats


# ---------------------------------------------------------------------------
# PRM v3
# ---------------------------------------------------------------------------

class CulturePRM_v3(nn.Module):
    """Process Reward Model for GRPO scoring (frozen, eval mode on cuda:1)."""

    def __init__(self, prm_checkpoint_dir: str, backbone_path: str,
                 sft_adapter_path: str = None):
        super().__init__()

        base_model = AutoModelForCausalLM.from_pretrained(
            backbone_path, torch_dtype=torch.bfloat16,
            trust_remote_code=True, output_hidden_states=True,
        )

        if sft_adapter_path:
            print(f"  [PRM] Merging SFT adapter into PRM backbone: {sft_adapter_path}")
            base_model = PeftModel.from_pretrained(base_model, sft_adapter_path)
            base_model = base_model.merge_and_unload()

        adapter_path = Path(prm_checkpoint_dir) / "adapter_model.safetensors"
        adapter_path_bin = Path(prm_checkpoint_dir) / "adapter_model.bin"
        if adapter_path.exists() or adapter_path_bin.exists():
            self.model = PeftModel.from_pretrained(base_model, prm_checkpoint_dir)
            print(f"  [PRM] Loaded PRM LoRA adapter from {prm_checkpoint_dir}")
        else:
            self.model = base_model
            print(f"  [PRM] No PRM adapter found, using backbone directly")

        hidden_size = base_model.config.hidden_size
        self.score_head = nn.Linear(hidden_size, 1)
        head_path = Path(prm_checkpoint_dir) / "score_head.pt"
        if head_path.exists():
            state = torch.load(head_path, map_location="cpu")
            self.score_head.load_state_dict(state)
            print(f"  [PRM] Loaded score_head from {head_path}")
        else:
            print(f"  [PRM] WARNING: score_head.pt not found at {head_path}")

        self.sigmoid = nn.Sigmoid()

    @torch.no_grad()
    def score_batch(self, input_texts: list, tokenizer, device,
                    max_len: int = 512) -> list:
        """Batch-score reasoning paths. Returns list of mean step scores."""
        if not input_texts:
            return []

        all_step_positions = []
        valid_indices = []
        for i, text in enumerate(input_texts):
            positions = self._find_step_positions(text, tokenizer, max_len)
            all_step_positions.append(positions)
            if positions:
                valid_indices.append(i)

        if not valid_indices:
            return [0.5] * len(input_texts)

        valid_texts = [input_texts[i] for i in valid_indices]
        enc = tokenizer(
            valid_texts, max_length=max_len, truncation=True,
            padding=True, return_tensors="pt",
        ).to(device)

        outputs = self.model(
            input_ids=enc["input_ids"],
            attention_mask=enc["attention_mask"],
            output_hidden_states=True,
        )
        hidden_states = outputs.hidden_states[-1]

        results = [0.5] * len(input_texts)
        seq_len = hidden_states.size(1)

        for batch_pos, orig_idx in enumerate(valid_indices):
            step_positions = all_step_positions[orig_idx]
            scores = []
            for pos in step_positions:
                if pos >= seq_len:
                    pos = seq_len - 1
                h = hidden_states[batch_pos, pos, :]
                logit = self.score_head(h.float()).squeeze(-1)
                score = self.sigmoid(logit).item()
                scores.append(score)
            if scores:
                mean_score = sum(scores) / len(scores)
                results[orig_idx] = max(0.1, min(0.9, mean_score))

        return results

    def _find_step_positions(self, text: str, tokenizer, max_len: int) -> list:
        """Find token positions of each step's last token."""
        step_starts = [m.start() for m in re.finditer(r'\[Step \d+\]', text)]
        if not step_starts:
            return []

        enc = tokenizer(
            text, max_length=max_len, truncation=True,
            return_offsets_mapping=True, add_special_tokens=True,
        )
        offsets = enc["offset_mapping"]

        end_positions = []
        for i, start_char in enumerate(step_starts):
            if i + 1 < len(step_starts):
                end_char = step_starts[i + 1] - 1
            else:
                end_char = len(text) - 1

            end_tok_pos = 0
            for tok_idx, (s, e) in enumerate(offsets):
                if e > 0 and s <= end_char:
                    end_tok_pos = tok_idx
            end_positions.append(end_tok_pos)

        return end_positions


# ---------------------------------------------------------------------------
# Data
# ---------------------------------------------------------------------------

class GRPOPromptDataset(Dataset):
    """Each item is a (query, country, gold_answer) dict."""
    def __init__(self, samples: list):
        self.items = []
        for obj in samples:
            self.items.append({
                "query": obj["query"],
                "country": obj.get("country", ""),
                "gt": str(obj["gt"]).strip(),
            })

    def __len__(self):
        return len(self.items)

    def __getitem__(self, idx):
        return self.items[idx]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def build_prompt(query: str, country: str, tokenizer) -> str:
    """Build culture-conditioned prompt."""
    content = f"[{country}]\n{query}\n\nReasoning: "
    messages = [{"role": "user", "content": content}]
    return tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )


def extract_answer(text: str):
    """Extract answer from generated response."""
    m = re.search(r"Answer\s*:\s*([1-4])", text, re.IGNORECASE)
    if m:
        return m.group(1)
    m = re.search(r"answer\s+is\s*:?\s*([1-4])\b", text, re.IGNORECASE)
    if m:
        return m.group(1)
    digits = re.findall(r"\b([1-4])\b", text)
    return digits[-1] if digits else None


def compute_r_outcome(predicted, gold: str) -> float:
    """Binary outcome reward."""
    return 1.0 if predicted == gold else 0.0


def build_prm_input(country: str, query: str, reasoning: str) -> str:
    """Build PRM input text with step markers."""
    steps = split_reasoning_into_steps(reasoning)
    if not steps:
        steps = [f"[Step 1] {reasoning}"]
    step_text = "\n".join(steps)
    return f"[{country}]\n{query}\n{step_text}"


def rloo_advantages(rewards: torch.Tensor) -> torch.Tensor:
    """
    RLOO (Reinforce Leave-One-Out) advantage estimation.
    rewards: (n_prompts, n_samples), returns same shape.
    """
    n = rewards.size(1)
    group_sum = rewards.sum(dim=1, keepdim=True)
    baseline = (group_sum - rewards) / max(n - 1, 1)
    return rewards - baseline


# ---------------------------------------------------------------------------
# Optimized Batch Generate (Optimization 1)
# ---------------------------------------------------------------------------

@torch.no_grad()
def batch_generate_responses(
    model, tokenizer, prompts: list, n_samples: int,
    max_new_tokens: int, temperature: float, device,
    mini_batch_size: int = 4,
) -> list:
    """
    Generate n_samples responses per prompt using BATCHED generation.

    Instead of generating one prompt at a time (serial), we batch multiple
    prompts together for much higher GPU utilization.

    Memory control: mini_batch_size prompts * n_samples sequences at once.
    With mini_batch_size=4, n_samples=5: 20 sequences simultaneously.
    Peak KV cache: ~20 * 640 tokens * 4096 hidden * 2 (K+V) * 28 layers * 2B
                 = ~4.5 GB (bf16). Fits comfortably in 48GB.

    Args:
        mini_batch_size: Prompts per generation call (default: 4).
            Reduce to 2 if OOM during generation.

    Returns:
        all_responses[prompt_idx] = [resp_0, ..., resp_{n_samples-1}]
    """
    all_responses = [[] for _ in range(len(prompts))]

    for start in range(0, len(prompts), mini_batch_size):
        batch_prompts = prompts[start:start + mini_batch_size]
        batch_size = len(batch_prompts)

        # Left-pad tokenization for batch generation
        enc = tokenizer(
            batch_prompts,
            return_tensors="pt",
            padding=True,
            max_length=MAX_PROMPT_LEN,
            truncation=True,
        ).to(device)

        # Generate n_samples per prompt in one call
        outs = model.generate(
            **enc,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=temperature,
            num_return_sequences=n_samples,
            pad_token_id=tokenizer.pad_token_id,
        )
        # outs shape: (batch_size * n_samples, seq_len)
        # Output interleaving: [p0_s0, p0_s1, ..., p0_sN, p1_s0, ...]

        prompt_lens = enc["attention_mask"].sum(dim=1)  # actual token counts

        for bi in range(batch_size):
            prompt_len = prompt_lens[bi].item()
            for si in range(n_samples):
                out_idx = bi * n_samples + si
                response_ids = outs[out_idx][prompt_len:]
                response = tokenizer.decode(response_ids, skip_special_tokens=True)
                all_responses[start + bi].append(response)

    return all_responses


# ---------------------------------------------------------------------------
# Optimized Batch Log-Prob Computation (Optimization 2)
# ---------------------------------------------------------------------------

def batch_compute_logprobs(
    model, tokenizer, prompts: list, responses: list,
    device, require_grad: bool = False, mini_batch_size: int = 8,
) -> list:
    """
    Compute mean log-prob of response tokens for multiple (prompt, response) pairs
    in batched forward passes.

    Instead of N serial forward passes, we batch them into groups of
    mini_batch_size for much higher throughput.

    Memory-efficient: computes log-prob via (target_logit - logsumexp) to avoid
    materializing full (batch, seq_len, vocab_size) softmax output.

    Args:
        prompts: List of prompt strings.
        responses: List of response strings (same length as prompts).
        require_grad: Whether to keep computation graph (True for Phase B).
        mini_batch_size: Sequences per forward pass.
            Phase A (no grad): use 8-10.
            Phase B (with grad): use 4 to limit activation memory.

    Returns:
        List of mean log-prob values (torch.Tensor if require_grad, else float).
    """
    assert len(prompts) == len(responses)
    n = len(prompts)
    results = [None] * n

    for start in range(0, n, mini_batch_size):
        end = min(start + mini_batch_size, n)
        batch_texts = [prompts[i] + responses[i] for i in range(start, end)]
        batch_prompts_slice = [prompts[i] for i in range(start, end)]

        # Tokenize full texts (prompt + response)
        enc_full = tokenizer(
            batch_texts,
            return_tensors="pt",
            padding=True,
            max_length=MAX_PROMPT_LEN + MAX_GEN_LEN,
            truncation=True,
        ).to(device)

        # Get prompt lengths to know where response starts
        prompt_lengths = []
        for p in batch_prompts_slice:
            p_enc = tokenizer(p, max_length=MAX_PROMPT_LEN, truncation=True)
            prompt_lengths.append(len(p_enc["input_ids"]))

        # Forward pass with appropriate gradient context
        ctx = torch.enable_grad() if require_grad else torch.no_grad()
        with ctx:
            outputs = model(
                input_ids=enc_full["input_ids"],
                attention_mask=enc_full["attention_mask"],
            )
            logits = outputs.logits  # (batch, seq_len, vocab)

            # Compute per-token log-probs for response portion only
            for bi in range(end - start):
                idx = start + bi
                p_len = prompt_lengths[bi]
                seq_len_i = int(enc_full["attention_mask"][bi].sum().item())

                if p_len >= seq_len_i:
                    # No response tokens
                    if require_grad:
                        results[idx] = torch.tensor(
                            0.0, device=device, requires_grad=True)
                    else:
                        results[idx] = 0.0
                    continue

                # Response logits: predict token[p_len:seq_len] from position[p_len-1:seq_len-1]
                resp_logits = logits[bi, p_len - 1:seq_len_i - 1, :]  # (resp_len, vocab)
                resp_targets = enc_full["input_ids"][bi, p_len:seq_len_i]  # (resp_len,)

                # Memory-efficient log-prob: gather + logsumexp
                # Instead of full log_softmax (materializes vocab-sized tensor)
                target_logits = resp_logits.gather(
                    1, resp_targets.unsqueeze(1)
                ).squeeze(1)  # (resp_len,)
                logsumexp_vals = resp_logits.float().logsumexp(dim=-1)  # (resp_len,)
                token_logprobs = target_logits.float() - logsumexp_vals  # (resp_len,)

                mean_lp = token_logprobs.mean()

                if require_grad:
                    results[idx] = mean_lp
                else:
                    results[idx] = mean_lp.item()

    return results


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

@torch.no_grad()
def validate(model, tokenizer, val_samples: list, device,
             max_samples: int = 200) -> float:
    """Compute validation accuracy (greedy decoding)."""
    model.eval()
    correct, total = 0, 0
    for obj in val_samples:
        if total >= max_samples:
            break
        prompt = build_prompt(obj["query"], obj.get("country", ""), tokenizer)
        enc = tokenizer(
            prompt, return_tensors="pt",
            max_length=MAX_PROMPT_LEN, truncation=True
        ).to(device)
        outs = model.generate(
            **enc, max_new_tokens=MAX_GEN_LEN,
            do_sample=False, temperature=None, top_p=None,
            pad_token_id=tokenizer.pad_token_id,
        )
        prompt_len = enc["input_ids"].shape[1]
        response = tokenizer.decode(outs[0][prompt_len:], skip_special_tokens=True)
        pred = extract_answer(response)
        if pred == str(obj["gt"]).strip():
            correct += 1
        total += 1
    model.train()
    return correct / total if total > 0 else 0.0


# ---------------------------------------------------------------------------
# Main training loop
# ---------------------------------------------------------------------------

def train(args):
    if not args.no_prm and args.prm_path is None:
        raise ValueError("--prm_path is required when PRM scoring is enabled. "
                         "Use --no_prm to skip PRM scoring.")

    policy_device = torch.device("cuda:0")
    prm_device = torch.device(
        "cuda:1" if torch.cuda.device_count() > 1 else "cuda:0")

    model_path = args.model_name

    # ---- Load Guardian index ----
    guardian_index = None
    if args.guardian_data:
        guardian_index = load_guardian_index(args.guardian_data)

    print(f"{'=' * 60}")
    print(f"CAMA-D CGM-GRPO: Culture-Guided Mixed-Policy GRPO")
    print(f"{'=' * 60}")
    print(f"Base model:    {model_path}")
    print(f"SFT adapter:   {args.sft_adapter or 'None (RL-only mode)'}")
    print(f"PRM path:      {args.prm_path}")
    print(f"Policy device: {policy_device}")
    print(f"PRM device:    {prm_device}")
    print(f"Alpha:         {args.alpha}")
    print(f"KL coef:       {KL_COEF}")
    print(f"LoRA rank:     {args.lora_r}")
    print(f"Guardian:      lambda={args.guardian_lambda}, "
          f"w_culture_mode={args.w_culture_mode}")
    print(f"Optimizations: Batch Generate (mini_batch={args.gen_mini_batch}), "
          f"Batch LogProb (ref={args.logprob_mini_batch}, "
          f"grad={args.logprob_mini_batch_grad})")

    # ---- Load data from pkl ----
    print(f"\nLoading data splits from: {args.data_pkl}")
    with open(args.data_pkl, "rb") as f:
        splits = pickle.load(f)
    train_data = splits["train"]
    val_data = splits["val"]

    # Apply --max_train_samples limit
    if args.max_train_samples > 0:
        train_data = train_data[:args.max_train_samples]
        print(f"  [SUBSET MODE] Using only {len(train_data)} training samples")

    print(f"  Data: train={len(train_data)}, val={len(val_data)}, "
          f"test={len(splits['test'])}")

    # ---- Compute culture maps (for w_culture) ----
    rarity_map, affinity_map = build_culture_maps(
        train_data, args.affinity_config
    )
    print(f"  Rarity map: {len(rarity_map)} country keywords")
    if affinity_map:
        print(f"  Affinity map: {len(affinity_map)} country keywords")

    # ---- Tokenizer ----
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "left"  # Required for batch generation

    # ---- Build Policy model (cuda:0) ----
    print(f"\nLoading base model: {model_path}")
    base_model = AutoModelForCausalLM.from_pretrained(
        model_path, torch_dtype=torch.bfloat16, trust_remote_code=True
    )

    if args.sft_adapter:
        print(f"  Merging SFT LoRA adapter: {args.sft_adapter}")
        base_model = PeftModel.from_pretrained(base_model, args.sft_adapter)
        base_model = base_model.merge_and_unload()
        print(f"  SFT adapter merged into base model")

    # Apply new GRPO LoRA (this is what we train)
    lora_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        r=args.lora_r,
        lora_alpha=args.lora_alpha,
        lora_dropout=0.05,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                        "gate_proj", "up_proj", "down_proj"],
        bias="none",
    )
    policy = get_peft_model(base_model, lora_config).to(policy_device)
    policy.print_trainable_parameters()
    policy.enable_input_require_grads()
    policy.gradient_checkpointing_enable()

    # ---- PRM (frozen, on cuda:1) ----
    if not args.no_prm:
        prm_backbone = args.prm_backbone if args.prm_backbone else model_path
        print(f"\nLoading PRM on {prm_device}: {args.prm_path}")
        prm = CulturePRM_v3(
            prm_checkpoint_dir=args.prm_path,
            backbone_path=prm_backbone,
            sft_adapter_path=args.sft_adapter,
        ).to(prm_device)
        prm_tokenizer = AutoTokenizer.from_pretrained(
            prm_backbone, trust_remote_code=True
        )
        if prm_tokenizer.pad_token is None:
            prm_tokenizer.pad_token = prm_tokenizer.eos_token
        for p in prm.parameters():
            p.requires_grad_(False)
        prm.eval()
    else:
        prm = None
        prm_tokenizer = None
        print("  [PRM] Skipped (--no_prm mode)")

    # ---- Optimizer ----
    trainable_params = [p for p in policy.parameters() if p.requires_grad]
    optimizer = torch.optim.AdamW(
        trainable_params, lr=args.lr, weight_decay=0.0, betas=(0.9, 0.95)
    )

    # ---- Dataset & DataLoader ----
    grpo_ds = GRPOPromptDataset(train_data)
    loader = DataLoader(
        grpo_ds, batch_size=args.prompt_batch, shuffle=True, pin_memory=False
    )

    Path(args.output_dir).mkdir(parents=True, exist_ok=True)
    best_val_acc = 0.0
    no_improve = 0

    effective_batches = (
        len(loader) if args.batches_per_round < 0
        else min(args.batches_per_round, len(loader))
    )
    print(f"\n{'=' * 60}")
    print(f"GRPO prompts: {len(grpo_ds)} | "
          f"Rounds: {args.max_rounds} | n_samples: {args.n_samples}")
    print(f"Batches per round: {effective_batches} "
          f"(prompt_batch={args.prompt_batch})")
    print(f"Starting CGM-GRPO training...")
    print(f"{'=' * 60}")
    sys.stdout.flush()

    # ---- Training rounds ----
    for rnd in range(1, args.max_rounds + 1):
        round_loss = 0.0
        round_steps = 0
        round_r_outcome = 0.0
        round_r_total = 0.0
        round_w_culture = 0.0
        round_s_guardian = 0.0
        round_guardian_applied = 0
        round_n = 0

        for batch_idx, batch in enumerate(loader):
            if batch_idx >= effective_batches:
                break

            queries = batch["query"]
            countries = batch["country"]
            golds = batch["gt"]
            n_prompts = len(queries)

            if batch_idx % 5 == 0:
                print(f"  Round {rnd} | Batch {batch_idx+1}/{effective_batches} "
                      f"| {n_prompts}x{args.n_samples} samples", flush=True)

            # ===== Step 1: Build prompts =====
            prompts = [build_prompt(q, c, tokenizer)
                       for q, c in zip(queries, countries)]

            # ===== Step 2: BATCH GENERATE (Optimization 1) =====
            policy.eval()
            policy.gradient_checkpointing_disable()
            all_responses = batch_generate_responses(
                policy, tokenizer, prompts,
                n_samples=args.n_samples,
                max_new_tokens=MAX_GEN_LEN,
                temperature=args.temperature,
                device=policy_device,
                mini_batch_size=args.gen_mini_batch,
            )
            policy.gradient_checkpointing_enable()
            policy.train()
            torch.cuda.empty_cache()

            # ===== Step 3: Compute rewards =====
            rewards = torch.zeros(n_prompts, args.n_samples, device=policy_device)
            r_outcomes = []

            for pi, (responses_i, gold) in enumerate(zip(all_responses, golds)):
                for si, resp in enumerate(responses_i):
                    pred = extract_answer(resp)
                    r_outcomes.append(compute_r_outcome(pred, str(gold).strip()))

            # PRM scoring (on cuda:1, parallel with cuda:0 idle)
            if args.no_prm:
                r_processes = [0.0] * (n_prompts * args.n_samples)
            else:
                prm_inputs = []
                for pi in range(n_prompts):
                    for si in range(args.n_samples):
                        prm_inputs.append(build_prm_input(
                            countries[pi], queries[pi], all_responses[pi][si]
                        ))

                PRM_BATCH_SIZE = 20
                r_processes = []
                for i in range(0, len(prm_inputs), PRM_BATCH_SIZE):
                    batch_texts = prm_inputs[i:i + PRM_BATCH_SIZE]
                    batch_scores = prm.score_batch(
                        batch_texts, prm_tokenizer, prm_device, max_len=512
                    )
                    r_processes.extend(batch_scores)

            # Combine outcome + process rewards
            idx = 0
            for pi in range(n_prompts):
                for si in range(args.n_samples):
                    r_out = r_outcomes[idx]
                    r_proc = r_processes[idx]
                    if args.no_prm:
                        r_total = r_out
                    else:
                        r_total = args.alpha * r_out + (1 - args.alpha) * r_proc
                    rewards[pi, si] = r_total
                    round_r_outcome += r_out
                    round_r_total += r_total
                    round_n += 1
                    idx += 1

            # ===== Step 4: RLOO advantages (on-policy only) =====
            advantages = rloo_advantages(rewards)

            # ===== Step 5: CGM-GRPO Guardian bonus =====
            if guardian_index is not None:
                advantages, g_stats = apply_cgm_guardian_bonus(
                    advantages=advantages,
                    rewards=rewards,
                    queries=queries,
                    countries=countries,
                    golds=golds,
                    r_outcomes=r_outcomes,
                    guardian_index=guardian_index,
                    guardian_lambda=args.guardian_lambda,
                    w_culture_mode=args.w_culture_mode,
                    rarity_map=rarity_map,
                    affinity_map=affinity_map,
                    n_samples=args.n_samples,
                )
                round_w_culture += g_stats["mean_w_culture"]
                round_s_guardian += g_stats["mean_s_guardian"]
                round_guardian_applied += g_stats["n_applied"]

            # ===== Step 6: BATCH POLICY GRADIENT (Optimization 2) =====
            total_samples = n_prompts * args.n_samples

            # Flatten: keep only samples with non-zero advantage
            flat_prompts = []
            flat_responses = []
            flat_advantages = []
            for pi in range(n_prompts):
                for si in range(args.n_samples):
                    adv = advantages[pi, si].item()
                    if abs(adv) < 1e-8:
                        continue
                    flat_prompts.append(prompts[pi])
                    flat_responses.append(all_responses[pi][si])
                    flat_advantages.append(adv)

            if not flat_prompts:
                continue

            # Phase A: Batch reference log-probs (no gradient, adapter disabled)
            policy.eval()
            policy.gradient_checkpointing_disable()
            with policy.disable_adapter():
                ref_logprobs = batch_compute_logprobs(
                    policy, tokenizer, flat_prompts, flat_responses,
                    policy_device, require_grad=False,
                    mini_batch_size=args.logprob_mini_batch,
                )
            torch.cuda.empty_cache()

            # Phase B: Policy forward+backward with gradient accumulation
            policy.gradient_checkpointing_enable()
            policy.train()
            optimizer.zero_grad()
            accumulated_loss = 0.0
            loss_count = 0

            pb_batch = args.logprob_mini_batch_grad
            for mb_start in range(0, len(flat_prompts), pb_batch):
                mb_end = min(mb_start + pb_batch, len(flat_prompts))
                mb_prompts = flat_prompts[mb_start:mb_end]
                mb_responses = flat_responses[mb_start:mb_end]
                mb_advantages = flat_advantages[mb_start:mb_end]
                mb_ref_lps = ref_logprobs[mb_start:mb_end]

                # Batch forward for policy log-probs (with grad)
                policy_lps = batch_compute_logprobs(
                    policy, tokenizer, mb_prompts, mb_responses,
                    policy_device, require_grad=True,
                    mini_batch_size=pb_batch,
                )

                # Compute loss for this mini-batch
                mb_loss = torch.tensor(0.0, device=policy_device)
                for i in range(len(mb_prompts)):
                    lp_policy = policy_lps[i]
                    lp_ref = mb_ref_lps[i]
                    adv = mb_advantages[i]

                    if not isinstance(lp_policy, torch.Tensor):
                        continue
                    if not lp_policy.requires_grad:
                        continue

                    lp_ref_t = torch.tensor(lp_ref, device=policy_device)
                    kl = (lp_policy - lp_ref_t).clamp(min=-10, max=10)
                    # GRPO loss: maximize advantage-weighted log-prob, penalize KL
                    pg_loss = -(adv * lp_policy - KL_COEF * kl)
                    mb_loss = mb_loss + pg_loss

                # Normalize and backward
                if mb_loss.requires_grad:
                    mb_loss = mb_loss / max(total_samples, 1)
                    mb_loss.backward()
                    accumulated_loss += mb_loss.item()
                    loss_count += 1

            # Gradient step
            if loss_count > 0:
                torch.nn.utils.clip_grad_norm_(trainable_params, 1.0)
                optimizer.step()
                round_loss += accumulated_loss
                round_steps += 1

            # Periodic memory cleanup
            if batch_idx % 10 == 0:
                torch.cuda.empty_cache()

        # ===== Round summary =====
        avg_loss = round_loss / max(round_steps, 1)
        avg_r_outcome = round_r_outcome / max(round_n, 1)
        avg_r_total = round_r_total / max(round_n, 1)
        avg_w = round_w_culture / max(round_guardian_applied, 1)
        avg_s = round_s_guardian / max(round_guardian_applied, 1)

        print(f"\n  Round {rnd}/{args.max_rounds} summary: "
              f"loss={avg_loss:.4f} | "
              f"R_out={avg_r_outcome:.3f} | "
              f"R_tot={avg_r_total:.3f} | "
              f"w_cul={avg_w:.3f} | "
              f"S_g={avg_s:.3f} | "
              f"guardian_applied={round_guardian_applied}\n")

        # Validation every eval_every rounds
        if rnd % args.eval_every == 0:
            val_acc = validate(policy, tokenizer, val_data, policy_device)
            print(f"  [Eval] Round {rnd} | val_accuracy={val_acc:.4f}")

            if val_acc > best_val_acc:
                best_val_acc = val_acc
                no_improve = 0
                ckpt = Path(args.output_dir) / "best"
                policy.save_pretrained(str(ckpt))
                tokenizer.save_pretrained(str(ckpt))
                print(f"  Saved best (val_acc={best_val_acc:.4f}) -> {ckpt}")
            else:
                no_improve += 1
                print(f"  No improvement ({no_improve}/{args.patience})")
                if no_improve >= args.patience:
                    print("  Early stopping triggered.")
                    break

    # Save final model if no validation was run
    if best_val_acc == 0.0:
        ckpt = Path(args.output_dir) / "best"
        policy.save_pretrained(str(ckpt))
        tokenizer.save_pretrained(str(ckpt))
        print(f"  Saved final model -> {ckpt}")

    print(f"\nTraining complete. Best val_accuracy: {best_val_acc:.4f}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="CAMA-D CGM-GRPO: Culture-Guided Mixed-Policy GRPO"
    )

    # Model & data
    parser.add_argument("--model_name", type=str, required=True,
                        help="'llama', 'qwen', or full HuggingFace model path")
    parser.add_argument("--sft_adapter", type=str, default=None,
                        help="Stage 1 SFT LoRA adapter path (for SFT+RL mode)")
    parser.add_argument("--data_pkl", type=str, required=True,
                        help="Path to splits pkl (from split_data.py)")
    parser.add_argument("--prm_path", type=str, default=None,
                        help="PRM checkpoint directory")
    parser.add_argument("--prm_backbone", type=str, default=None,
                        help="PRM backbone path (defaults to base model)")
    parser.add_argument("--output_dir", type=str, required=True,
                        help="Directory to save checkpoints")

    # Training hyperparams
    parser.add_argument("--alpha", type=float, default=DEFAULT_ALPHA,
                        help="R_outcome weight in R_total (default: 0.6)")
    parser.add_argument("--n_samples", type=int, default=5,
                        help="Rollout samples per prompt (default: 5)")
    parser.add_argument("--temperature", type=float, default=0.7,
                        help="Generation temperature (default: 0.7)")
    parser.add_argument("--max_rounds", type=int, default=20,
                        help="Max training rounds (default: 20)")
    parser.add_argument("--eval_every", type=int, default=5,
                        help="Validation every N rounds (default: 5)")
    parser.add_argument("--patience", type=int, default=3,
                        help="Early stop patience (default: 3)")
    parser.add_argument("--prompt_batch", type=int, default=8,
                        help="Prompts per GRPO batch (default: 8)")
    parser.add_argument("--lr", type=float, default=5e-5,
                        help="Learning rate (default: 5e-5)")
    parser.add_argument("--lora_r", type=int, default=16,
                        help="LoRA rank (default: 16)")
    parser.add_argument("--lora_alpha", type=int, default=32,
                        help="LoRA alpha (default: 32)")
    parser.add_argument("--batches_per_round", type=int, default=130,
                        help="Max batches per round (-1 = all, default: 130)")
    parser.add_argument("--no_prm", action="store_true",
                        help="Disable PRM scoring (R_total = R_outcome only)")

    # Sample limit
    parser.add_argument("--max_train_samples", type=int, default=0,
                        help="Max training samples. 0=all, N=first N samples.")

    # CGM-GRPO specific
    parser.add_argument("--guardian_data", type=str, default=None,
                        help="HF-CAC inference JSONL with Guardian responses")
    parser.add_argument("--guardian_lambda", type=float, default=0.5,
                        help="Guardian guidance strength (default: 0.5)")
    parser.add_argument("--w_culture_mode", type=str, default="hit_only",
                        choices=["hit_only", "hit_rarity", "full"],
                        help="w_culture computation mode (default: hit_only)")
    parser.add_argument("--affinity_config", type=str, default=None,
                        help="Path to hf_cac_config.yaml (for hit_rarity/full)")

    # Batch optimization params
    parser.add_argument("--gen_mini_batch", type=int, default=4,
                        help="Prompts per batch-generate call (default: 4). "
                             "Reduce to 2 if OOM during generation.")
    parser.add_argument("--logprob_mini_batch", type=int, default=8,
                        help="Samples per batch in Phase A ref log-prob "
                             "(no grad, default: 8).")
    parser.add_argument("--logprob_mini_batch_grad", type=int, default=4,
                        help="Samples per batch in Phase B policy log-prob "
                             "(with grad, default: 4). Reduce if OOM.")

    args = parser.parse_args()

    # Resolve model alias
    args.model_name = MODEL_ALIASES.get(args.model_name, args.model_name)

    train(args)


if __name__ == "__main__":
    main()
