"""
CAMAD: Culture-Aware Adaptive Mixed Distillation (joint SFT+RL).

Core method (see camad.md §6.2):
  - Trains DIRECTLY FROM THE BASE MODEL (no separate SFT warm-up stage). The
    supervised signal is injected ONLINE via the joint loss below. This is the
    key difference from classic RLHF (base -> SFT -> RL): by mixing SFT and RL
    in one optimization step from the base, CAMAD avoids the catastrophic
    forgetting that the staged SFT->RL pipeline suffers from.
  - Joint objective in ONE optimization step:
        L = L_GRPO(A_i) + beta * w_sft * L_SFT
  - RL part (exploration + cultural guidance):
        A_i = A_i^base + lambda_g * w * S_guardian          (per-rollout)
    where A_i^base = R_i - mean(R) is the standard GRPO/RLOO advantage,
    S_guardian in {0,1} indicates whether the rollout's CULTURAL REASONING
    DIRECTION matches the Guardian's judgment (per-rollout).
  - SFT part (Judge distillation, anti-forgetting):
        L_SFT = -log P(y_judge | x),  weighted by w_sft.
    y_judge = HF-CAC Judge final answer (the multi-agent decision).
  - Difficulty-adaptive weights (shared per-prompt hitrate, tracked by EMA):
        w     = 1 - hitrate                         (RL guidance weight, ->0)
        w_sft = max(1 - hitrate, w_min)             (SFT weight, with floor)

Note on Guardian signal semantics:
  HF-CAC inference JSONL stores Guardian/Judge as parsed answer DIGITS only
  (no separate "cultural direction" field). We therefore use the Guardian's
  answer choice as the proxy for cultural direction: S_guardian = 1 iff the
  rollout's parsed choice equals the Guardian's choice. When richer cultural
  direction labels become available in the data, plug them into
  `guardian_cultural_match()` without changing the training loop.

Performance optimizations (inherited):
  - Batch Generate: all prompts in one model.generate() call.
  - Batch LogProb: vectorized forward pass for ref/policy log-probs.
  - Mini-batch backward: accumulate gradients over small groups.

Architecture (LoRA, no DeepSpeed):
  - Policy: BASE model + new trainable LoRA on cuda:0 (joint SFT+RL trained;
    NO pre-merged SFT adapter)
  - Reference: same model with adapter disabled (zero extra memory)
  - PRM: loaded on cuda:1 for parallel scoring (frozen, eval mode)

Hardware requirement: 2x vGPU-48GB (policy on cuda:0, PRM on cuda:1)

Usage:
    # Quick test with 10 samples (trains from BASE; no SFT adapter)
    python Cul/grpo/train_grpo_mixed_policy.py \\
        --model_name     qwen \\
        --data_pkl       /path/to/normad_splits.pkl \\
        --prm_path       /path/to/camad_prm/best \\
        --guardian_data  /path/to/normad_hf_cac_inference.jsonl \\
        --output_dir     /path/to/models/camad \\
        --max_samples    10 \\
        --max_rounds     3 \\
        --n_samples      5

    # Full CAMAD joint SFT+RL training (from BASE model)
    python Cul/grpo/train_grpo_mixed_policy.py \\
        --model_name     qwen \\
        --data_pkl       /path/to/normad_splits.pkl \\
        --prm_path       /path/to/camad_prm/best \\
        --guardian_data  /path/to/normad_hf_cac_inference.jsonl \\
        --output_dir     /path/to/models/camad \\
        --beta           0.3 \\
        --lambda_g       0.5 \\
        --w_min          0.1 \\
        --n_samples      5 \\
        --max_rounds     20 \\
        --batches_per_round 130

    The --data_pkl file should be generated by split_data.py.
    The --guardian_data is the HF-CAC inference JSONL from Stage 0
    (provides both Guardian signal and Judge SFT target).
"""

import re
import os
import json
import math
import pickle
import argparse
import sys
from pathlib import Path

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import LoraConfig, get_peft_model, PeftModel, TaskType

# Import step splitting utility
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from step_label.split_steps import split_reasoning_into_steps


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MODEL_ALIASES = {
    "llama": "/root/autodl-tmp/base/Meta-Llama-3.1-8B-Instruct",
    "qwen":  "/root/autodl-tmp/base/Qwen2.5-7B-Instruct",
}

MAX_GEN_LEN = 128
MAX_PROMPT_LEN = 512
KL_COEF = 0.05
DEFAULT_ALPHA = 0.6


# ---------------------------------------------------------------------------
# Shared utilities
# ---------------------------------------------------------------------------

def limit_train_samples(train_samples, args):
    """
    Cap the number of training samples for a quick smoke run.

    Priority: --max_samples (0 = use ALL, the default) takes precedence; if it
    is 0 we fall back to the legacy --max_train_samples (>0 caps, the historical
    default of -1/0 means "all"). Shared by all three ablations (SFT-only /
    RL-only / CAMAD) so e.g. `--max_samples 10` trains on only 10 samples.
    """
    n = getattr(args, "max_samples", 0)
    if not n or n <= 0:
        legacy = getattr(args, "max_train_samples", 0)
        n = legacy if legacy and legacy > 0 else 0
    if n and n > 0:
        return train_samples[:n]
    return train_samples


# ---------------------------------------------------------------------------
# HF-CAC Data Loading (Guardian signal + Judge SFT target)
# ---------------------------------------------------------------------------

def load_hf_cac_index(jsonl_path: str) -> dict:
    """
    Load HF-CAC inference JSONL and build a lookup index keyed by
    (country_lower, query_prefix_lower).

    Each value carries both:
      - guardian_answer : Guardian's parsed choice digit (cultural direction proxy)
      - judge_answer    : Judge's final decision digit  (SFT distillation target)
      - judge_text      : Judge's final answer text (for richer SFT target)

    Returns:
        dict[(country, query_prefix)] -> {
            "guardian_answer": str | None,
            "judge_answer": str | None,
            "judge_text": str,
        }
    """
    index = {}
    n_guardian = 0
    n_judge = 0
    with open(jsonl_path, "r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            obj = json.loads(line)
            query = obj.get("query", "").strip()
            country = obj.get("country", "").strip()
            response = obj.get("response", "")

            guardian_text = _extract_guardian_text(response)
            guardian_answer = (_extract_answer_digit(guardian_text)
                               if guardian_text else None)
            judge_text = _extract_judge_text(response)
            judge_answer = (_extract_answer_digit(judge_text)
                            if judge_text else None)

            if guardian_answer is not None:
                n_guardian += 1
            if judge_answer is not None:
                n_judge += 1

            key = (country.lower(), query[:200].lower())
            index[key] = {
                "guardian_answer": guardian_answer,
                "judge_answer": judge_answer,
                "judge_text": judge_text,
            }

    print(f"  [HF-CAC] Loaded {len(index)} records from {jsonl_path} "
          f"(guardian={n_guardian}, judge={n_judge})")
    return index


def _extract_guardian_text(formatted_response: str) -> str:
    """Extract Guardian's text block from formatted multi-agent response."""
    pattern = r'===== Solution \d+ \[GUARDIAN\] =====\n(.*?)(?=\n===== Solution|\Z)'
    match = re.search(pattern, formatted_response, re.DOTALL)
    if match:
        return match.group(1).strip()
    return ""


def _extract_judge_text(formatted_response: str) -> str:
    """Extract Judge's text block (handles all judge mode tags)."""
    pattern = r'===== Solution \d+ \[JUDGE[^\]]*\] =====\n(.*?)(?=\n===== Solution|\Z)'
    match = re.search(pattern, formatted_response, re.DOTALL)
    if match:
        return match.group(1).strip()
    return ""


def _extract_answer_digit(text: str) -> str:
    """Extract an answer digit (1-4) from an agent text block."""
    if not text:
        return None
    first_line = text.split("\n")[0].strip()
    m = re.match(r'^([1-4])\b', first_line)
    if m:
        return m.group(1)
    m = re.search(r"Answer\s*:\s*([1-4])", text, re.IGNORECASE)
    if m:
        return m.group(1)
    digits = re.findall(r"\b([1-4])\b", text)
    return digits[0] if digits else None


def lookup_hf_cac(index: dict, country: str, query: str) -> dict:
    """Look up an HF-CAC record by (country, query prefix)."""
    if not index:
        return None
    key = (country.lower().strip(), query[:200].lower().strip())
    return index.get(key, None)


# ---------------------------------------------------------------------------
# Difficulty-adaptive weights: per-prompt hitrate tracked by EMA
# ---------------------------------------------------------------------------

class HitRateTracker:
    """
    Track per-prompt hitrate (cultural mastery) with optional EMA smoothing,
    and derive the RL guidance weight w and the SFT weight w_sft.

        w     = 1 - hitrate                       (can decay to 0)
        w_sft = max(1 - hitrate, w_min)           (floored, anti-forgetting)

    hitrate update:
        EMA on:  hitrate <- m * prev + (1 - m) * acc_cur
        EMA off: hitrate <- acc_cur                (current-round value)
    """

    def __init__(self, w_min: float = 0.1, momentum: float = 0.9,
                 use_ema: bool = True):
        self.w_min = w_min
        self.momentum = momentum
        self.use_ema = use_ema
        self._hitrate = {}  # prompt_key -> float

    @staticmethod
    def _key(country: str, query: str) -> tuple:
        return (country.lower().strip(), query[:200].lower().strip())

    def update(self, country: str, query: str, acc_cur: float) -> float:
        """Update and return the smoothed hitrate for a prompt."""
        key = self._key(country, query)
        if self.use_ema and key in self._hitrate:
            prev = self._hitrate[key]
            hr = self.momentum * prev + (1.0 - self.momentum) * acc_cur
        else:
            hr = acc_cur
        self._hitrate[key] = hr
        return hr

    def weights(self, hitrate: float) -> tuple:
        """Return (w, w_sft) given a hitrate."""
        w = max(0.0, 1.0 - hitrate)
        w_sft = max(w, self.w_min)
        return w, w_sft


def guardian_cultural_match(rollout_pred: str, guardian_answer: str) -> int:
    """
    Per-rollout cultural-direction signal S_guardian in {0, 1}.

    Defined as whether the rollout's cultural reasoning DIRECTION matches the
    Guardian's judgment. With the current HF-CAC data (answer digits only), we
    use the Guardian's answer choice as the cultural-direction proxy:
        S_guardian = 1 iff rollout_pred == guardian_answer.

    If a future data format provides an explicit cultural-direction label for
    each rollout, replace this comparison accordingly (the training loop is
    agnostic to how this 0/1 is computed).
    """
    if guardian_answer is None or rollout_pred is None:
        return 0
    return 1 if str(rollout_pred).strip() == str(guardian_answer).strip() else 0


# ---------------------------------------------------------------------------
# PRM v3
# ---------------------------------------------------------------------------

class CulturePRM_v3(nn.Module):
    """Process Reward Model for GRPO scoring (frozen, eval mode on cuda:1)."""

    def __init__(self, prm_checkpoint_dir: str, backbone_path: str,
                 sft_adapter_path: str = None):
        super().__init__()

        base_model = AutoModelForCausalLM.from_pretrained(
            backbone_path, torch_dtype=torch.bfloat16,
            trust_remote_code=True, output_hidden_states=True,
        )

        if sft_adapter_path:
            print(f"  [PRM] Merging SFT adapter into PRM backbone: {sft_adapter_path}")
            base_model = PeftModel.from_pretrained(base_model, sft_adapter_path)
            base_model = base_model.merge_and_unload()

        adapter_path = Path(prm_checkpoint_dir) / "adapter_model.safetensors"
        adapter_path_bin = Path(prm_checkpoint_dir) / "adapter_model.bin"
        if adapter_path.exists() or adapter_path_bin.exists():
            self.model = PeftModel.from_pretrained(base_model, prm_checkpoint_dir)
            print(f"  [PRM] Loaded PRM LoRA adapter from {prm_checkpoint_dir}")
        else:
            self.model = base_model
            print(f"  [PRM] No PRM adapter found, using backbone directly")

        hidden_size = base_model.config.hidden_size
        self.score_head = nn.Linear(hidden_size, 1)
        head_path = Path(prm_checkpoint_dir) / "score_head.pt"
        if head_path.exists():
            state = torch.load(head_path, map_location="cpu")
            self.score_head.load_state_dict(state)
            print(f"  [PRM] Loaded score_head from {head_path}")
        else:
            print(f"  [PRM] WARNING: score_head.pt not found at {head_path}")

        self.sigmoid = nn.Sigmoid()

    @torch.no_grad()
    def score_batch(self, input_texts: list, tokenizer, device,
                    max_len: int = 512) -> list:
        """Batch-score reasoning paths. Returns list of mean step scores."""
        if not input_texts:
            return []

        all_step_positions = []
        valid_indices = []
        for i, text in enumerate(input_texts):
            positions = self._find_step_positions(text, tokenizer, max_len)
            all_step_positions.append(positions)
            if positions:
                valid_indices.append(i)

        if not valid_indices:
            return [0.5] * len(input_texts)

        valid_texts = [input_texts[i] for i in valid_indices]
        enc = tokenizer(
            valid_texts, max_length=max_len, truncation=True,
            padding=True, return_tensors="pt",
        ).to(device)

        outputs = self.model(
            input_ids=enc["input_ids"],
            attention_mask=enc["attention_mask"],
            output_hidden_states=True,
        )
        hidden_states = outputs.hidden_states[-1]

        results = [0.5] * len(input_texts)
        seq_len = hidden_states.size(1)

        for batch_pos, orig_idx in enumerate(valid_indices):
            step_positions = all_step_positions[orig_idx]
            scores = []
            for pos in step_positions:
                if pos >= seq_len:
                    pos = seq_len - 1
                h = hidden_states[batch_pos, pos, :]
                logit = self.score_head(h.float()).squeeze(-1)
                score = self.sigmoid(logit).item()
                scores.append(score)
            if scores:
                mean_score = sum(scores) / len(scores)
                results[orig_idx] = max(0.1, min(0.9, mean_score))

        return results

    def _find_step_positions(self, text: str, tokenizer, max_len: int) -> list:
        """Find token positions of each step's last token."""
        step_starts = [m.start() for m in re.finditer(r'\[Step \d+\]', text)]
        if not step_starts:
            return []

        enc = tokenizer(
            text, max_length=max_len, truncation=True,
            return_offsets_mapping=True, add_special_tokens=True,
        )
        offsets = enc["offset_mapping"]

        end_positions = []
        for i, start_char in enumerate(step_starts):
            if i + 1 < len(step_starts):
                end_char = step_starts[i + 1] - 1
            else:
                end_char = len(text) - 1

            end_tok_pos = 0
            for tok_idx, (s, e) in enumerate(offsets):
                if e > 0 and s <= end_char:
                    end_tok_pos = tok_idx
            end_positions.append(end_tok_pos)

        return end_positions


# ---------------------------------------------------------------------------
# Data
# ---------------------------------------------------------------------------

class GRPOPromptDataset(Dataset):
    """Each item is a (query, country, gold_answer) dict."""
    def __init__(self, samples: list):
        self.items = []
        for obj in samples:
            self.items.append({
                "query": obj["query"],
                "country": obj.get("country", ""),
                "gt": str(obj["gt"]).strip(),
            })

    def __len__(self):
        return len(self.items)

    def __getitem__(self, idx):
        return self.items[idx]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def build_prompt(query: str, country: str, tokenizer) -> str:
    """Build culture-conditioned prompt."""
    content = f"[{country}]\n{query}\n\nReasoning: "
    messages = [{"role": "user", "content": content}]
    return tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )


def build_judge_sft_target(judge_answer: str, judge_text: str) -> str:
    """
    Build the SFT distillation target from the Judge's final decision.

    Uses the Judge's final answer: answer-first digit plus a short rationale
    line (if present in judge_text). Falls back to "Answer: <digit>".
    """
    if judge_answer is None:
        return None
    # Take a short rationale: first non-empty line of judge_text that isn't
    # just the digit/tag, to keep the supervision focused on the final answer.
    rationale = ""
    for line in judge_text.split("\n"):
        s = line.strip()
        if not s:
            continue
        if re.fullmatch(r'[1-4]', s):
            continue
        if s.startswith("["):
            continue
        rationale = s
        break
    if rationale:
        return f"Answer: {judge_answer}\nReason: {rationale}"
    return f"Answer: {judge_answer}"


def extract_answer(text: str):
    """Extract answer from generated response."""
    m = re.search(r"Answer\s*:\s*([1-4])", text, re.IGNORECASE)
    if m:
        return m.group(1)
    m = re.search(r"answer\s+is\s*:?\s*([1-4])\b", text, re.IGNORECASE)
    if m:
        return m.group(1)
    digits = re.findall(r"\b([1-4])\b", text)
    return digits[-1] if digits else None


def compute_r_outcome(predicted, gold: str) -> float:
    """Binary outcome reward."""
    return 1.0 if predicted == gold else 0.0


def build_prm_input(country: str, query: str, reasoning: str) -> str:
    """Build PRM input text with step markers."""
    steps = split_reasoning_into_steps(reasoning)
    if not steps:
        steps = [f"[Step 1] {reasoning}"]
    step_text = "\n".join(steps)
    return f"[{country}]\n{query}\n{step_text}"


def grpo_advantages(rewards: torch.Tensor) -> torch.Tensor:
    """
    Standard GRPO advantage: A_i^base = R_i - mean(R) within each prompt group.
    rewards: (n_prompts, n_samples), returns same shape.
    """
    baseline = rewards.mean(dim=1, keepdim=True)
    return rewards - baseline


# ---------------------------------------------------------------------------
# Optimized Batch Generate (Optimization 1)
# ---------------------------------------------------------------------------

@torch.no_grad()
def batch_generate_responses(
    model, tokenizer, prompts: list, n_samples: int,
    max_new_tokens: int, temperature: float, device,
    mini_batch_size: int = 4,
) -> list:
    """
    Generate n_samples responses per prompt using BATCHED generation.

    Returns:
        all_responses[prompt_idx] = [resp_0, ..., resp_{n_samples-1}]
    """
    all_responses = [[] for _ in range(len(prompts))]

    for start in range(0, len(prompts), mini_batch_size):
        batch_prompts = prompts[start:start + mini_batch_size]
        batch_size = len(batch_prompts)

        enc = tokenizer(
            batch_prompts,
            return_tensors="pt",
            padding=True,
            max_length=MAX_PROMPT_LEN,
            truncation=True,
        ).to(device)

        outs = model.generate(
            **enc,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=temperature,
            num_return_sequences=n_samples,
            pad_token_id=tokenizer.pad_token_id,
        )

        prompt_lens = enc["attention_mask"].sum(dim=1)

        for bi in range(batch_size):
            prompt_len = prompt_lens[bi].item()
            for si in range(n_samples):
                out_idx = bi * n_samples + si
                response_ids = outs[out_idx][prompt_len:]
                response = tokenizer.decode(response_ids, skip_special_tokens=True)
                all_responses[start + bi].append(response)

    return all_responses


# ---------------------------------------------------------------------------
# Optimized Batch Log-Prob Computation (Optimization 2)
# ---------------------------------------------------------------------------

def batch_compute_logprobs(
    model, tokenizer, prompts: list, responses: list,
    device, require_grad: bool = False,
    mini_batch_size: int = 8,
) -> torch.Tensor:
    """
    Compute the sum of per-token log-probs of `responses` given `prompts`.

    prompts[i] corresponds to responses[i] (flat 1:1 lists).

    Returns:
        Tensor of shape (N,) with summed log-prob of each response.
        If require_grad=True, the returned tensor is part of the autograd graph.
    """
    assert len(prompts) == len(responses)
    n = len(prompts)
    out = [] if require_grad else torch.zeros(n, device=device)

    ctx = torch.enable_grad() if require_grad else torch.no_grad()
    with ctx:
        for start in range(0, n, mini_batch_size):
            b_prompts = prompts[start:start + mini_batch_size]
            b_resps = responses[start:start + mini_batch_size]

            full_texts = [p + r for p, r in zip(b_prompts, b_resps)]
            enc = tokenizer(
                full_texts, return_tensors="pt", padding=True,
                max_length=MAX_PROMPT_LEN + MAX_GEN_LEN, truncation=True,
            ).to(device)

            # Lengths of prompt-only parts (to mask out prompt tokens).
            prompt_enc = tokenizer(
                b_prompts, padding=False, truncation=True,
                max_length=MAX_PROMPT_LEN,
            )
            prompt_lens = [len(ids) for ids in prompt_enc["input_ids"]]

            logits = model(
                input_ids=enc["input_ids"],
                attention_mask=enc["attention_mask"],
            ).logits  # (B, T, V)

            log_probs = torch.log_softmax(logits[:, :-1, :], dim=-1)
            target_ids = enc["input_ids"][:, 1:]
            token_lp = log_probs.gather(
                2, target_ids.unsqueeze(-1)
            ).squeeze(-1)  # (B, T-1)

            attn = enc["attention_mask"][:, 1:]
            for bi in range(len(b_prompts)):
                p_len = prompt_lens[bi]
                # Response tokens start at index p_len in the full sequence;
                # in the shifted (T-1) space they start at p_len - 1.
                resp_start = max(0, p_len - 1)
                mask = attn[bi].clone().float()
                mask[:resp_start] = 0.0
                lp_sum = (token_lp[bi] * mask).sum()
                if require_grad:
                    out.append(lp_sum)
                else:
                    out[start + bi] = lp_sum.detach()

    if require_grad:
        return torch.stack(out)
    return out


def compute_sft_loss(
    model, tokenizer, prompts: list, targets: list, device,
    mini_batch_size: int = 4,
) -> torch.Tensor:
    """
    Supervised distillation loss L_SFT = mean(-log P(y_judge | x)) over the
    response tokens, returned WITH grad.

    prompts[i] pairs with targets[i] (Judge final-answer text). Entries with a
    None target are skipped. Returns a scalar tensor (0.0 if nothing to train).
    """
    pairs = [(p, t) for p, t in zip(prompts, targets) if t is not None]
    if not pairs:
        return torch.zeros((), device=device)

    total_nll = torch.zeros((), device=device)
    total_tokens = 0

    for start in range(0, len(pairs), mini_batch_size):
        batch = pairs[start:start + mini_batch_size]
        b_prompts = [p for p, _ in batch]
        b_targets = [t for _, t in batch]

        full_texts = [p + t for p, t in zip(b_prompts, b_targets)]
        enc = tokenizer(
            full_texts, return_tensors="pt", padding=True,
            max_length=MAX_PROMPT_LEN + MAX_GEN_LEN, truncation=True,
        ).to(device)

        prompt_enc = tokenizer(
            b_prompts, padding=False, truncation=True,
            max_length=MAX_PROMPT_LEN,
        )
        prompt_lens = [len(ids) for ids in prompt_enc["input_ids"]]

        logits = model(
            input_ids=enc["input_ids"],
            attention_mask=enc["attention_mask"],
        ).logits
        log_probs = torch.log_softmax(logits[:, :-1, :], dim=-1)
        target_ids = enc["input_ids"][:, 1:]
        token_lp = log_probs.gather(
            2, target_ids.unsqueeze(-1)
        ).squeeze(-1)
        attn = enc["attention_mask"][:, 1:]

        for bi in range(len(batch)):
            resp_start = max(0, prompt_lens[bi] - 1)
            mask = attn[bi].clone().float()
            mask[:resp_start] = 0.0
            n_tok = mask.sum()
            if n_tok.item() == 0:
                continue
            total_nll = total_nll + (-(token_lp[bi] * mask).sum())
            total_tokens += int(n_tok.item())

    if total_tokens == 0:
        return torch.zeros((), device=device)
    return total_nll / total_tokens


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

@torch.no_grad()
def validate(model, tokenizer, val_samples: list, device,
             max_eval: int = 100) -> float:
    """Greedy-decode accuracy on a validation subset."""
    model.eval()
    correct = 0
    total = 0
    subset = val_samples[:max_eval]

    for obj in subset:
        prompt = build_prompt(obj["query"], obj.get("country", ""), tokenizer)
        enc = tokenizer(
            prompt, return_tensors="pt",
            max_length=MAX_PROMPT_LEN, truncation=True,
        ).to(device)
        out = model.generate(
            **enc, max_new_tokens=MAX_GEN_LEN, do_sample=False,
            pad_token_id=tokenizer.pad_token_id,
        )
        response = tokenizer.decode(
            out[0][enc["input_ids"].shape[1]:], skip_special_tokens=True
        )
        pred = extract_answer(response)
        if pred == str(obj["gt"]).strip():
            correct += 1
        total += 1

    model.train()
    return correct / max(1, total)


# ---------------------------------------------------------------------------
# Ablation: SFT-only (camad.md §2.1)
# ---------------------------------------------------------------------------

def train_sft_only(args):
    """
    Ablation §2.1 SFT-only: train DIRECTLY FROM THE BASE model with ONLY the
    supervised distillation term, no RL branch at all.

    To keep this a strictly controlled ablation (口径 A), the supervised signal
    is IDENTICAL to CAMAD's online SFT term:
        - target  = Judge final answer y_judge   (build_judge_sft_target)
        - loss    = L_SFT = mean(-log P(y_judge | x))   (compute_sft_loss)
        - weight  = w_sft = max(1 - hitrate, w_min)     (HitRateTracker)

    The only differences vs CAMAD are that there is NO GRPO advantage term and
    NO Guardian guidance, i.e. the objective is just  beta * w_sft * L_SFT
    (beta defaults to 1.0 for SFT-only so the supervised term is not scaled
    down; pass --beta to override if you want the exact CAMAD scaling).

    Because there is no RL, this runs on a SINGLE GPU (cuda:0) and needs NO
    PRM. The hitrate that drives w_sft is estimated from a lightweight greedy
    decode of the current policy (n=1 per prompt), so the difficulty-adaptive
    weighting follows the exact same formula/path as CAMAD.
    """
    policy_device = torch.device("cuda:0")

    model_path = MODEL_ALIASES.get(args.model_name, args.model_name)
    print(f"[SFT-only] Base model: {model_path}")

    # --- Tokenizer ---
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "left"

    # --- Policy model: BASE + new trainable LoRA (supervised only) ---
    print("[SFT-only] Loading policy model (from BASE) ...")
    base = AutoModelForCausalLM.from_pretrained(
        model_path, torch_dtype=torch.bfloat16, trust_remote_code=True,
    )
    lora_cfg = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        r=args.lora_r, lora_alpha=args.lora_alpha,
        lora_dropout=0.05,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    )
    policy = get_peft_model(base, lora_cfg)
    policy.to(policy_device)
    policy.train()
    if args.grad_checkpoint:
        policy.gradient_checkpointing_enable()
        policy.enable_input_require_grads()
    policy.print_trainable_parameters()

    # --- Data ---
    with open(args.data_pkl, "rb") as f:
        splits = pickle.load(f)
    train_samples = splits["train"]
    val_samples = splits.get("val", splits.get("test", []))
    train_samples = limit_train_samples(train_samples, args)
    print(f"[SFT-only] Train={len(train_samples)}  Val={len(val_samples)}")

    train_ds = GRPOPromptDataset(train_samples)
    loader = DataLoader(
        train_ds, batch_size=args.prompt_batch_size,
        shuffle=True, collate_fn=lambda b: b,
    )

    # --- HF-CAC index (Judge SFT target; Guardian unused in SFT-only) ---
    hf_cac_index = {}
    if args.guardian_data:
        hf_cac_index = load_hf_cac_index(args.guardian_data)
    else:
        print("[SFT-only] WARNING: --guardian_data not provided; no Judge "
              "targets will be available and nothing will be learned.")

    # --- Difficulty-adaptive weight tracker (same as CAMAD) ---
    tracker = HitRateTracker(
        w_min=args.w_min, momentum=args.ema_momentum, use_ema=args.use_ema,
    )

    optimizer = torch.optim.AdamW(
        [p for p in policy.parameters() if p.requires_grad], lr=args.lr,
    )

    os.makedirs(args.output_dir, exist_ok=True)
    best_acc = 0.0
    global_step = 0

    print(f"[SFT-only] Hyper-params: beta={args.beta} w_min={args.w_min} "
          f"ema={args.use_ema}(m={args.ema_momentum})")

    # Total batches actually run per round (for progress display).
    total_batches = min(
        args.batches_per_round,
        math.ceil(len(train_samples) / args.prompt_batch_size),
    )

    for rnd in range(args.max_rounds):
        print(f"\n========== Round {rnd + 1}/{args.max_rounds} ==========")
        round_batches = 0

        for batch in loader:
            if round_batches >= args.batches_per_round:
                break
            round_batches += 1
            global_step += 1

            prompts = [
                build_prompt(s["query"], s["country"], tokenizer) for s in batch
            ]
            golds = [s["gt"] for s in batch]
            countries = [s["country"] for s in batch]
            queries = [s["query"] for s in batch]
            n_prompts = len(batch)

            # Lightweight progress: the greedy decode + SFT backward below are
            # silent and can take a while, so surface where we are each batch.
            print(f"  [SFT-only] round {rnd + 1}/{args.max_rounds} "
                  f"batch {round_batches}/{total_batches} "
                  f"(step {global_step}) | greedy decode {n_prompts} prompts "
                  f"...", flush=True)

            # ---- Estimate hitrate via a lightweight greedy decode (n=1) ----
            # This keeps w_sft on the exact same formula/path as CAMAD without
            # needing RL rollouts or a PRM.
            policy.eval()
            greedy_resps = batch_generate_responses(
                policy, tokenizer, prompts, n_samples=1,
                max_new_tokens=MAX_GEN_LEN, temperature=1.0,
                device=policy_device, mini_batch_size=args.gen_mini_batch,
            )
            policy.train()

            # ---- Build Judge SFT targets + per-prompt w_sft ----
            sft_prompts = []
            sft_targets = []
            sft_weights = []
            for pi in range(n_prompts):
                pred = extract_answer(greedy_resps[pi][0])
                acc_cur = 1.0 if pred == golds[pi] else 0.0
                hr = tracker.update(countries[pi], queries[pi], acc_cur)
                _, w_sft = tracker.weights(hr)

                rec = lookup_hf_cac(hf_cac_index, countries[pi], queries[pi])
                judge_ans = rec["judge_answer"] if rec else None
                judge_text = rec["judge_text"] if rec else ""
                target = build_judge_sft_target(judge_ans, judge_text)
                if target is not None:
                    sft_prompts.append(prompts[pi])
                    sft_targets.append(target)
                    sft_weights.append(w_sft)

            # ---- Supervised backward: beta * w_sft * L_SFT ----
            optimizer.zero_grad()
            if sft_prompts:
                l_sft = compute_sft_loss(
                    policy, tokenizer, sft_prompts, sft_targets,
                    policy_device, mini_batch_size=args.sft_mini_batch,
                )
                w_sft_mean = sum(sft_weights) / len(sft_weights)
                loss = args.beta * w_sft_mean * l_sft
                loss.backward()
                torch.nn.utils.clip_grad_norm_(
                    [p for p in policy.parameters() if p.requires_grad], 1.0
                )
                optimizer.step()
            else:
                l_sft = torch.zeros((), device=policy_device)
                loss = torch.zeros((), device=policy_device)
                w_sft_mean = 0.0

            if global_step % args.log_every == 0:
                print(
                    f"  step {global_step} | loss {loss.item():.4f} "
                    f"(sft {l_sft.item():.4f}) | w_sft {w_sft_mean:.3f} | "
                    f"targets {len(sft_prompts)}/{n_prompts}"
                )

        # ---- Validation per round ----
        if val_samples:
            n_eval = min(args.max_eval, len(val_samples)) if args.max_eval > 0 \
                else len(val_samples)
            print(f"  [SFT-only] round {rnd + 1} validating on {n_eval} "
                  f"samples ...", flush=True)
            acc = validate(
                policy, tokenizer, val_samples, policy_device,
                max_eval=args.max_eval,
            )
            print(f"[SFT-only] Round {rnd + 1} val acc = {acc:.4f}")
            if acc > best_acc:
                best_acc = acc
                save_path = os.path.join(args.output_dir, "best")
                policy.save_pretrained(save_path)
                tokenizer.save_pretrained(save_path)
                print(f"[SFT-only] New best ({acc:.4f}) saved to {save_path}")

    final_path = os.path.join(args.output_dir, "final")
    policy.save_pretrained(final_path)
    tokenizer.save_pretrained(final_path)
    print(f"[SFT-only] Training done. Best val acc = {best_acc:.4f}. "
          f"Final adapter saved to {final_path}")


# ---------------------------------------------------------------------------
# Training (CAMAD joint SFT + RL)
# ---------------------------------------------------------------------------

def train(args):
    policy_device = torch.device("cuda:0")
    prm_device = torch.device("cuda:1")

    # RL-only ablation (camad.md §2.2): plain GRPO from base, i.e. NO Guardian
    # advantage guidance and NO online SFT term. The reward stays the same
    # (alpha*R_outcome + PRM process), the advantage degenerates to A_i=A_base.
    rl_only = (getattr(args, "mode", "camad") == "rl_only")
    tag = "RL-only" if rl_only else "CAMAD"

    model_path = MODEL_ALIASES.get(args.model_name, args.model_name)
    print(f"[{tag}] Base model: {model_path}")

    # --- Tokenizer ---
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "left"  # left padding for generation

    # --- Policy model: BASE + new trainable LoRA ---
    # Both CAMAD and RL-only train directly from the base model. CAMAD injects
    # the supervised (SFT) signal ONLINE via the joint loss
    # L = L_GRPO + beta * w_sft * L_SFT, which is what distinguishes CAMAD's
    # "mixed" strategy from classic RLHF (base -> SFT -> RL) and avoids the
    # catastrophic forgetting of the staged pipeline. RL-only drops the SFT
    # term and the Guardian guidance, leaving plain GRPO.
    init_adapter = getattr(args, "init_adapter", None)
    if init_adapter:
        # SFT->RL stage 2 (camad.md §2.3): the RL stage starts FROM the SFT
        # checkpoint. We merge the SFT LoRA into the base weights so that (a)
        # the new trainable LoRA is initialized on top of the SFT-converged
        # model, and (b) the reference policy used by KL (policy.disable_adapter)
        # points at the SFT model -- i.e. RL is anchored on the SFT checkpoint,
        # exactly the classic RLHF semantics. This is ONLY a stage-2 starting
        # point; CAMAD / RL-only leave it None and start from the plain base.
        print(f"[{tag}] Loading policy model (from SFT checkpoint: "
              f"{init_adapter}) ...")
        base = AutoModelForCausalLM.from_pretrained(
            model_path, torch_dtype=torch.bfloat16, trust_remote_code=True,
        )
        base = PeftModel.from_pretrained(base, init_adapter)
        base = base.merge_and_unload()
    else:
        print(f"[{tag}] Loading policy model (from BASE, no SFT warm-up) ...")
        base = AutoModelForCausalLM.from_pretrained(
            model_path, torch_dtype=torch.bfloat16, trust_remote_code=True,
        )

    lora_cfg = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        r=args.lora_r, lora_alpha=args.lora_alpha,
        lora_dropout=0.05,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    )
    policy = get_peft_model(base, lora_cfg)
    policy.to(policy_device)
    policy.train()
    if args.grad_checkpoint:
        policy.gradient_checkpointing_enable()
        policy.enable_input_require_grads()
    policy.print_trainable_parameters()

    # --- PRM (frozen, cuda:1) ---
    # The PRM is an independently trained scorer. --prm_sft_adapter only needs
    # to be set if the PRM was trained on a base that had an SFT adapter merged
    # in; for the CAMAD-from-base setup the PRM should likewise be trained on
    # the plain base model, so this is None by default.
    print(f"[{tag}] Loading PRM ...")
    prm = CulturePRM_v3(
        prm_checkpoint_dir=args.prm_path,
        backbone_path=model_path,
        sft_adapter_path=args.prm_sft_adapter,
    )
    prm.to(prm_device)
    prm.eval()

    # --- Data ---
    with open(args.data_pkl, "rb") as f:
        splits = pickle.load(f)
    train_samples = splits["train"]
    val_samples = splits.get("val", splits.get("test", []))
    train_samples = limit_train_samples(train_samples, args)
    print(f"[{tag}] Train={len(train_samples)}  Val={len(val_samples)}")

    train_ds = GRPOPromptDataset(train_samples)
    loader = DataLoader(
        train_ds, batch_size=args.prompt_batch_size,
        shuffle=True, collate_fn=lambda b: b,
    )

    # --- HF-CAC index (Guardian signal + Judge SFT target) ---
    hf_cac_index = {}
    if args.guardian_data:
        hf_cac_index = load_hf_cac_index(args.guardian_data)

    # --- Difficulty-adaptive weight tracker ---
    tracker = HitRateTracker(
        w_min=args.w_min, momentum=args.ema_momentum, use_ema=args.use_ema,
    )

    # --- Optimizer ---
    optimizer = torch.optim.AdamW(
        [p for p in policy.parameters() if p.requires_grad], lr=args.lr,
    )

    os.makedirs(args.output_dir, exist_ok=True)
    best_acc = 0.0
    global_step = 0

    print(f"[{tag}] Hyper-params: beta={args.beta} lambda_g={args.lambda_g} "
          f"w_min={args.w_min} ema={args.use_ema}(m={args.ema_momentum}) "
          f"alpha={args.alpha} n_samples={args.n_samples}"
          + (" | plain GRPO (no Guardian, no SFT)" if rl_only else ""))

    # Total batches actually run per round (for progress display).
    total_batches = min(
        args.batches_per_round,
        math.ceil(len(train_samples) / args.prompt_batch_size),
    )

    for rnd in range(args.max_rounds):
        print(f"\n========== Round {rnd + 1}/{args.max_rounds} ==========")
        round_batches = 0

        for batch in loader:
            if round_batches >= args.batches_per_round:
                break
            round_batches += 1
            global_step += 1

            # ---- Step 1: build prompts ----
            prompts = [
                build_prompt(s["query"], s["country"], tokenizer) for s in batch
            ]
            golds = [s["gt"] for s in batch]
            countries = [s["country"] for s in batch]
            queries = [s["query"] for s in batch]
            n_prompts = len(batch)

            # Lightweight progress: the generate/PRM/backward below are silent
            # and can take a while, so surface where we are each batch.
            print(f"  [{tag}] round {rnd + 1}/{args.max_rounds} "
                  f"batch {round_batches}/{total_batches} "
                  f"(step {global_step}) | generating {n_prompts}x"
                  f"{args.n_samples} rollouts ...", flush=True)

            # ---- Step 2: batch generate n_samples rollouts each ----
            policy.eval()
            all_responses = batch_generate_responses(
                policy, tokenizer, prompts, args.n_samples,
                MAX_GEN_LEN, args.temperature, policy_device,
                mini_batch_size=args.gen_mini_batch,
            )
            policy.train()

            # ---- Step 3: rewards (outcome + PRM process) ----
            rewards = torch.zeros(n_prompts, args.n_samples, device=policy_device)
            preds = [[None] * args.n_samples for _ in range(n_prompts)]

            # Outcome reward + parse predictions.
            for pi in range(n_prompts):
                for si in range(args.n_samples):
                    resp = all_responses[pi][si]
                    pred = extract_answer(resp)
                    preds[pi][si] = pred
                    rewards[pi, si] += compute_r_outcome(pred, golds[pi])

            # PRM process reward (batched on cuda:1).
            prm_inputs = []
            prm_map = []
            for pi in range(n_prompts):
                for si in range(args.n_samples):
                    txt = build_prm_input(
                        countries[pi], queries[pi], all_responses[pi][si]
                    )
                    prm_inputs.append(txt)
                    prm_map.append((pi, si))
            prm_scores = prm.score_batch(
                prm_inputs, tokenizer, prm_device, max_len=MAX_PROMPT_LEN
            )
            for (pi, si), sc in zip(prm_map, prm_scores):
                rewards[pi, si] += args.alpha * sc

            # ---- Step 4: GRPO base advantages ----
            adv = grpo_advantages(rewards)  # (n_prompts, n_samples)

            # ---- Step 5: per-prompt hitrate + per-rollout Guardian signal ----
            # w / w_sft per prompt (shared across its rollouts).
            w_per_prompt = []
            w_sft_per_prompt = []
            judge_targets = []  # SFT target per prompt (Judge final answer)
            for pi in range(n_prompts):
                acc_cur = sum(
                    1 for si in range(args.n_samples)
                    if preds[pi][si] == golds[pi]
                ) / args.n_samples
                hr = tracker.update(countries[pi], queries[pi], acc_cur)
                w, w_sft = tracker.weights(hr)
                w_per_prompt.append(w)
                w_sft_per_prompt.append(w_sft)

                rec = lookup_hf_cac(hf_cac_index, countries[pi], queries[pi])
                guardian_ans = rec["guardian_answer"] if rec else None
                judge_ans = rec["judge_answer"] if rec else None
                judge_text = rec["judge_text"] if rec else ""
                judge_targets.append(
                    build_judge_sft_target(judge_ans, judge_text)
                )

                # A_i = A_base + lambda_g * w * S_guardian  (per-rollout).
                # RL-only: skip Guardian guidance -> advantage stays A_base.
                if not rl_only:
                    for si in range(args.n_samples):
                        s_guard = guardian_cultural_match(
                            preds[pi][si], guardian_ans
                        )
                        adv[pi, si] = adv[pi, si] + args.lambda_g * w * s_guard

            # ---- Step 6: joint backward  L = L_GRPO + beta * w_sft * L_SFT ----
            # Flatten rollouts for GRPO log-probs.
            flat_prompts = []
            flat_resps = []
            flat_adv = []
            for pi in range(n_prompts):
                for si in range(args.n_samples):
                    flat_prompts.append(prompts[pi])
                    flat_resps.append(all_responses[pi][si])
                    flat_adv.append(adv[pi, si].item())
            flat_adv_t = torch.tensor(flat_adv, device=policy_device)

            # Reference log-probs (adapter disabled -> base policy).
            with policy.disable_adapter():
                lp_ref = batch_compute_logprobs(
                    policy, tokenizer, flat_prompts, flat_resps,
                    policy_device, require_grad=False,
                    mini_batch_size=args.logprob_mini_batch,
                )

            optimizer.zero_grad()

            # Policy log-probs WITH grad -> GRPO loss.
            lp_policy = batch_compute_logprobs(
                policy, tokenizer, flat_prompts, flat_resps,
                policy_device, require_grad=True,
                mini_batch_size=args.logprob_mini_batch,
            )
            kl = (lp_policy - lp_ref).clamp(min=-10, max=10)
            pg_loss = -(flat_adv_t * lp_policy - KL_COEF * kl)
            l_grpo = pg_loss.mean()

            # Judge SFT loss (weighted per prompt by w_sft).
            # RL-only: no online SFT term at all -> skip building it entirely
            # (avoids a wasted forward pass even if --guardian_data is given).
            sft_prompts = []
            sft_targets = []
            sft_weights = []
            if not rl_only:
                for pi in range(n_prompts):
                    if judge_targets[pi] is not None:
                        sft_prompts.append(prompts[pi])
                        sft_targets.append(judge_targets[pi])
                        sft_weights.append(w_sft_per_prompt[pi])

            if sft_prompts:
                # Weighted SFT: the loss is token-normalized, so we scale it by
                # the mean w_sft over the prompts that contributed a target.
                l_sft = compute_sft_loss(
                    policy, tokenizer, sft_prompts, sft_targets,
                    policy_device, mini_batch_size=args.sft_mini_batch,
                )
                w_sft_mean = sum(sft_weights) / len(sft_weights)
                l_sft_weighted = w_sft_mean * l_sft
            else:
                l_sft = torch.zeros((), device=policy_device)
                l_sft_weighted = torch.zeros((), device=policy_device)

            loss = l_grpo + args.beta * l_sft_weighted
            loss.backward()
            torch.nn.utils.clip_grad_norm_(
                [p for p in policy.parameters() if p.requires_grad], 1.0
            )
            optimizer.step()

            if global_step % args.log_every == 0:
                mean_w = sum(w_per_prompt) / len(w_per_prompt)
                mean_w_sft = sum(w_sft_per_prompt) / len(w_sft_per_prompt)
                mean_r = rewards.mean().item()
                print(
                    f"  step {global_step} | loss {loss.item():.4f} "
                    f"(grpo {l_grpo.item():.4f}, sft {l_sft.item():.4f}) | "
                    f"meanR {mean_r:.3f} | w {mean_w:.3f} w_sft {mean_w_sft:.3f}"
                )

        # ---- Validation per round ----
        if val_samples:
            n_eval = min(args.max_eval, len(val_samples)) if args.max_eval > 0 \
                else len(val_samples)
            print(f"  [{tag}] round {rnd + 1} validating on {n_eval} "
                  f"samples ...", flush=True)
            acc = validate(
                policy, tokenizer, val_samples, policy_device,
                max_eval=args.max_eval,
            )
            print(f"[{tag}] Round {rnd + 1} val acc = {acc:.4f}")
            if acc > best_acc:
                best_acc = acc
                save_path = os.path.join(args.output_dir, "best")
                policy.save_pretrained(save_path)
                tokenizer.save_pretrained(save_path)
                print(f"[{tag}] New best ({acc:.4f}) saved to {save_path}")

    # Final save.
    final_path = os.path.join(args.output_dir, "final")
    policy.save_pretrained(final_path)
    tokenizer.save_pretrained(final_path)
    print(f"[{tag}] Training done. Best val acc = {best_acc:.4f}. "
          f"Final adapter saved to {final_path}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    p = argparse.ArgumentParser(
        description="CAMAD: Culture-Aware Adaptive Mixed Distillation "
                    "(joint SFT+RL)"
    )
    # Mode
    p.add_argument("--mode", choices=["camad", "sft_only", "rl_only"],
                   default="camad",
                   help="camad = joint SFT+RL (default); "
                        "sft_only = ablation §2.1 (supervised distillation "
                        "only, single GPU, no PRM); "
                        "rl_only = ablation §2.2 (plain GRPO from base, no "
                        "Guardian guidance, no online SFT; needs PRM)")

    # Paths
    p.add_argument("--model_name", default="qwen",
                   help="alias (llama/qwen) or HF path")
    p.add_argument("--prm_sft_adapter", default=None,
                   help="(optional) SFT-LoRA adapter to merge into the PRM "
                        "backbone, ONLY if the PRM was trained on an "
                        "SFT-merged base. The policy is ALWAYS trained from "
                        "the plain base model (CAMAD has no SFT warm-up).")
    p.add_argument("--data_pkl", required=True,
                   help="splits pickle from split_data.py (train/val/test)")
    p.add_argument("--prm_path", default=None,
                   help="PRM checkpoint dir (adapter + score_head.pt). "
                        "Required for --mode camad and --mode rl_only; "
                        "unused for --mode sft_only.")
    p.add_argument("--guardian_data", default=None,
                   help="HF-CAC inference JSONL (Guardian signal + Judge SFT "
                        "target), from generate_hf_cac_data.py")
    p.add_argument("--init_adapter", default=None,
                   help="(optional) SFT-LoRA adapter to MERGE into the base as "
                        "the RL starting point. Used by SFT->RL stage 2 "
                        "(camad.md §2.3) so RL starts from the SFT checkpoint. "
                        "Leave unset for CAMAD / RL-only / SFT-only (start "
                        "from plain base).")
    p.add_argument("--output_dir", required=True)

    # CAMAD joint objective
    p.add_argument("--beta", type=float, default=0.3,
                   help="balance coefficient for SFT term: "
                        "L = L_GRPO + beta * w_sft * L_SFT (0.1~0.5)")
    p.add_argument("--lambda_g", type=float, default=0.5,
                   help="Guardian global strength: A_i += lambda_g * w * S_guardian")
    p.add_argument("--w_min", type=float, default=0.1,
                   help="floor for the SFT weight: w_sft = max(1-hitrate, w_min)")
    p.add_argument("--use_ema", action="store_true", default=True,
                   help="use EMA-smoothed hitrate (default on)")
    p.add_argument("--no_ema", dest="use_ema", action="store_false",
                   help="disable EMA, use current-round hitrate")
    p.add_argument("--ema_momentum", type=float, default=0.9,
                   help="EMA momentum for hitrate smoothing")
    p.add_argument("--alpha", type=float, default=DEFAULT_ALPHA,
                   help="PRM process-reward weight")

    # GRPO / sampling
    p.add_argument("--n_samples", type=int, default=5,
                   help="rollouts per prompt (group size)")
    p.add_argument("--temperature", type=float, default=0.9)
    p.add_argument("--max_rounds", type=int, default=20)
    p.add_argument("--batches_per_round", type=int, default=130)
    p.add_argument("--prompt_batch_size", type=int, default=4)
    p.add_argument("--max_samples", type=int, default=0,
                   help="cap #training samples for a quick smoke run; "
                        "0 = use ALL (default). e.g. --max_samples 10 trains "
                        "on only 10 samples. Applies to all three ablations.")
    p.add_argument("--max_train_samples", type=int, default=0,
                   help="(deprecated) legacy alias; prefer --max_samples. "
                        ">0 caps #train samples, 0 = all.")
    p.add_argument("--max_eval", type=int, default=100)

    # LoRA / optim
    p.add_argument("--lora_r", type=int, default=16)
    p.add_argument("--lora_alpha", type=int, default=32)
    p.add_argument("--lr", type=float, default=1e-5)
    p.add_argument("--grad_checkpoint", action="store_true", default=True)

    # Batching for the optimizations
    p.add_argument("--gen_mini_batch", type=int, default=4)
    p.add_argument("--logprob_mini_batch", type=int, default=8)
    p.add_argument("--sft_mini_batch", type=int, default=4)

    # Logging
    p.add_argument("--log_every", type=int, default=10)

    args = p.parse_args()

    if args.mode in ("camad", "rl_only"):
        if not args.prm_path:
            p.error(f"--prm_path is required for --mode {args.mode}")
        train(args)
    else:  # sft_only
        train_sft_only(args)


if __name__ == "__main__":
    main()