"""
CAMA-D Stage 3-GRPO: GRPO with Mean(R_process) Reward — LoRA 版本（无 DeepSpeed）

Key innovations over old GRPO (train_grpo.py):
  - R_total = alpha * R_outcome + (1-alpha) * Mean(R_process)
  - PRM uses step-level scoring (Sigmoid at each [Step N] terminator)
  - Mean(R_process) ∈ [0.1, 0.9] — perfectly aligned with R_outcome ∈ {0, 1}
  - Heuristic step splitting before PRM scoring (same rules as Stage 2)
  - alpha=0.6 (outcome-dominant, process as soft constraint)

Architecture (LoRA, no DeepSpeed):
  - Policy: base model + SFT-LoRA merged + new GRPO-LoRA (trainable)
  - Reference: same base model with adapter disabled (zero extra memory)
  - PRM: loaded on cuda:1 for parallel scoring
  - Gradient checkpointing enabled for memory efficiency

Hardware requirement: 2×vGPU-48GB (policy on cuda:0, PRM on cuda:1)

Usage:
    # SFT+RL (from Stage 1 SFT LoRA — recommended)
    python Cul/grpo/train_grpo_v3.py \\
        --model_name     qwen \\
        --sft_adapter    /path/to/camad_sft_qwen/best \\
        --data_pkl       /path/to/normad_splits.pkl \\
        --prm_path       /path/to/camad_prm/best \\
        --output_dir     /path/to/models/camad_grpo_sft_qwen \\
        --alpha          0.6 \\
        --n_samples      10 \\
        --max_rounds     20 \\
        --eval_every     5

    # RL-only (from base model, no SFT adapter)
    python Cul/grpo/train_grpo_v3.py \\
        --model_name     qwen \\
        --data_pkl       /path/to/normad_splits.pkl \\
        --prm_path       /path/to/camad_prm/best \\
        --prm_backbone   /path/to/base_model \\
        --output_dir     /path/to/models/camad_grpo_qwen \\
        --alpha          0.6 \\
        --n_samples      10 \\
        --max_rounds     30 \\
        --eval_every     5

    The --data_pkl file should be generated by split_data.py (contains train/val/test splits).
"""

import re
import os
import json
import pickle
import argparse
from pathlib import Path

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import LoraConfig, get_peft_model, PeftModel, TaskType

# Import step splitting utility
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from step_label.split_steps import split_reasoning_into_steps


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MODEL_ALIASES = {
    "llama": "/root/autodl-tmp/base/Meta-Llama-3.1-8B-Instruct",
    "qwen":  "/root/autodl-tmp/base/Qwen2.5-7B-Instruct",
}

MAX_GEN_LEN = 512
MAX_PROMPT_LEN = 512
KL_COEF = 0.05       # KL penalty coefficient
DEFAULT_ALPHA = 0.6   # R_outcome weight


# ---------------------------------------------------------------------------
# PRM v3: Step-level scoring with Sigmoid (matches train_prm_mse.py)
# ---------------------------------------------------------------------------

class CulturePRM_v3(nn.Module):
    """
    Process Reward Model for GRPO scoring.

    Loads the trained PRM (backbone + LoRA + score_head) and scores
    each step in a reasoning path. Returns Mean(scores) as R_process.

    Architecture matches train_prm_mse.py:
      - Backbone: base model + SFT-LoRA merged (same as PRM training time)
      - PRM LoRA adapter on top
      - score_head: Linear(hidden, 1) + Sigmoid → (0, 1)
      - Scoring at [Step N] terminator positions
    """

    def __init__(self, prm_checkpoint_dir: str, backbone_path: str,
                 sft_adapter_path: str = None):
        super().__init__()

        # Load base model
        base_model = AutoModelForCausalLM.from_pretrained(
            backbone_path,
            torch_dtype=torch.bfloat16,
            trust_remote_code=True,
            output_hidden_states=True,
        )

        # Merge SFT LoRA into base (to match PRM training backbone)
        if sft_adapter_path:
            print(f"  [PRM-v3] Merging SFT adapter into PRM backbone: {sft_adapter_path}")
            base_model = PeftModel.from_pretrained(base_model, sft_adapter_path)
            base_model = base_model.merge_and_unload()

        # Load PRM LoRA adapter
        adapter_path = Path(prm_checkpoint_dir) / "adapter_model.safetensors"
        adapter_path_bin = Path(prm_checkpoint_dir) / "adapter_model.bin"
        if adapter_path.exists() or adapter_path_bin.exists():
            self.model = PeftModel.from_pretrained(base_model, prm_checkpoint_dir)
            print(f"  [PRM-v3] Loaded PRM LoRA adapter from {prm_checkpoint_dir}")
        else:
            self.model = base_model
            print(f"  [PRM-v3] No PRM adapter found, using backbone directly")

        # Load score_head
        hidden_size = base_model.config.hidden_size
        self.score_head = nn.Linear(hidden_size, 1)
        head_path = Path(prm_checkpoint_dir) / "score_head.pt"
        if head_path.exists():
            state = torch.load(head_path, map_location="cpu")
            self.score_head.load_state_dict(state)
            print(f"  [PRM-v3] Loaded score_head from {head_path}")
        else:
            print(f"  [PRM-v3] WARNING: score_head.pt not found at {head_path}")

        self.sigmoid = nn.Sigmoid()

    @torch.no_grad()
    def score_reasoning(
        self,
        input_text: str,
        tokenizer,
        device,
        max_len: int = 1024,
    ) -> float:
        """
        Score a full reasoning path and return Mean(R_process).

        Steps:
          1. Tokenize the full text with step markers
          2. Find step terminator positions
          3. Score each step via backbone + score_head + Sigmoid
          4. Return mean of all step scores

        Returns:
            Mean step score ∈ [0.1, 0.9] (clamped)
        """
        enc = tokenizer(
            input_text,
            max_length=max_len,
            truncation=True,
            return_tensors="pt",
        ).to(device)

        input_ids = enc["input_ids"]
        attention_mask = enc["attention_mask"]

        # Find [Step N] terminator positions
        step_positions = self._find_step_positions(input_text, tokenizer, max_len)

        if not step_positions:
            # No steps found — return neutral score
            return 0.5

        outputs = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            output_hidden_states=True,
        )
        hidden_states = outputs.hidden_states[-1]  # (1, seq_len, hidden)

        scores = []
        seq_len = hidden_states.size(1)
        for pos in step_positions:
            if pos >= seq_len:
                pos = seq_len - 1
            h = hidden_states[0, pos, :]
            logit = self.score_head(h.float()).squeeze(-1)
            score = self.sigmoid(logit).item()
            scores.append(score)

        mean_score = sum(scores) / len(scores)
        # Clamp to [0.1, 0.9] as designed
        return max(0.1, min(0.9, mean_score))

    def _find_step_positions(self, text: str, tokenizer, max_len: int) -> list[int]:
        """Find token positions of each step's last token."""
        import re as _re

        step_starts = [m.start() for m in _re.finditer(r'\[Step \d+\]', text)]
        if not step_starts:
            return []

        enc = tokenizer(
            text, max_length=max_len, truncation=True,
            return_offsets_mapping=True, add_special_tokens=True,
        )
        offsets = enc["offset_mapping"]

        end_positions = []
        for i, start_char in enumerate(step_starts):
            if i + 1 < len(step_starts):
                end_char = step_starts[i + 1] - 1
            else:
                end_char = len(text) - 1

            end_tok_pos = 0
            for tok_idx, (s, e) in enumerate(offsets):
                if e > 0 and s <= end_char:
                    end_tok_pos = tok_idx

            end_positions.append(end_tok_pos)

        return end_positions


# ---------------------------------------------------------------------------
# Data
# ---------------------------------------------------------------------------

class GRPOPromptDataset(Dataset):
    """Each item is a (query, country, gold_answer) tuple."""
    def __init__(self, samples: list[dict]):
        self.items = []
        for obj in samples:
            self.items.append({
                "query": obj["query"],
                "country": obj.get("country", ""),
                "gt": str(obj["gt"]).strip(),
            })

    def __len__(self):
        return len(self.items)

    def __getitem__(self, idx):
        return self.items[idx]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def build_prompt(query: str, country: str, tokenizer) -> str:
    """Build culture-conditioned prompt."""
    content = f"[{country}]\n{query}\n\nReasoning: "
    messages = [{"role": "user", "content": content}]
    return tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )


def extract_answer(text: str):
    """Extract answer from generated response."""
    m = re.search(r"Answer\s*:\s*([1-4])", text, re.IGNORECASE)
    if m:
        return m.group(1)
    m = re.search(r"answer\s+is\s*:?\s*([1-4])\b", text, re.IGNORECASE)
    if m:
        return m.group(1)
    digits = re.findall(r"\b([1-4])\b", text)
    return digits[-1] if digits else None


def compute_r_outcome(predicted, gold: str) -> float:
    """Binary outcome reward."""
    return 1.0 if predicted == gold else 0.0


def build_prm_input(country: str, query: str, reasoning: str) -> str:
    """
    Build PRM input text with step markers.

    Steps:
      1. Split reasoning into steps using heuristic rules
      2. Format as: [country]\\nquestion\\n[Step 1]...\\n[Step 2]...
    """
    steps = split_reasoning_into_steps(reasoning)
    if not steps:
        # If splitting fails, wrap entire reasoning as single step
        steps = [f"[Step 1] {reasoning}"]

    step_text = "\n".join(steps)
    return f"[{country}]\n{query}\n{step_text}"


def rloo_advantages(rewards: torch.Tensor) -> torch.Tensor:
    """
    RLOO (Reinforce Leave-One-Out) advantage estimation.

    rewards: (n_prompts, n_samples)
    baseline = mean of other samples in the group.
    """
    n = rewards.size(1)
    group_sum = rewards.sum(dim=1, keepdim=True)
    baseline = (group_sum - rewards) / max(n - 1, 1)
    return rewards - baseline


# ---------------------------------------------------------------------------
# Policy generation
# ---------------------------------------------------------------------------

@torch.no_grad()
def generate_responses(
    model, tokenizer, prompts: list, n_samples: int,
    max_new_tokens: int, temperature: float, device
) -> list:
    """Generate n_samples responses per prompt using num_return_sequences."""
    all_responses = []
    for prompt in prompts:
        enc = tokenizer(
            prompt, return_tensors="pt",
            max_length=MAX_PROMPT_LEN, truncation=True
        ).to(device)
        outs = model.generate(
            **enc,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=temperature,
            num_return_sequences=n_samples,
            pad_token_id=tokenizer.pad_token_id,
        )
        prompt_len = enc["input_ids"].shape[1]
        responses = [
            tokenizer.decode(o[prompt_len:], skip_special_tokens=True)
            for o in outs
        ]
        all_responses.append(responses)
    return all_responses


# ---------------------------------------------------------------------------
# Log-prob computation
# ---------------------------------------------------------------------------

def compute_logprobs(model, tokenizer, prompt: str, response: str, device,
                     require_grad: bool = False):
    """Return mean log-prob of response tokens given prompt.

    Memory-optimized: uses gather before log_softmax to avoid materializing
    the full (seq_len, vocab_size) log-prob tensor.

    Args:
        require_grad: If True, compute with gradients (for policy loss).
                      If False, compute under torch.no_grad() (for reference).
    """
    full_text = prompt + response
    enc = tokenizer(
        full_text, return_tensors="pt",
        max_length=MAX_PROMPT_LEN + MAX_GEN_LEN, truncation=True
    ).to(device)
    prompt_enc = tokenizer(
        prompt, return_tensors="pt",
        max_length=MAX_PROMPT_LEN, truncation=True
    )
    prompt_len = prompt_enc["input_ids"].shape[1]

    if require_grad:
        logits = model(**enc).logits  # (1, seq_len, vocab_size)
    else:
        with torch.no_grad():
            logits = model(**enc).logits

    # Only compute log-probs for response tokens (memory efficient)
    # logits at position [prompt_len-1 : -1] predict tokens at [prompt_len:]
    target_ids = enc["input_ids"][0, prompt_len:]  # (resp_len,)
    resp_logits = logits[0, prompt_len - 1: -1, :]  # (resp_len, vocab_size)

    if resp_logits.shape[0] == 0 or target_ids.shape[0] == 0:
        return torch.tensor(0.0, device=device, requires_grad=require_grad)

    n = min(resp_logits.shape[0], target_ids.shape[0])
    resp_logits = resp_logits[:n]
    target_ids = target_ids[:n]

    # Compute log-prob only for target tokens using log_softmax + gather
    # This is more memory-efficient than materializing full log_probs matrix
    log_probs = F.log_softmax(resp_logits, dim=-1)  # (n, vocab_size)
    gathered = log_probs.gather(1, target_ids.unsqueeze(1)).squeeze(1)  # (n,)
    return gathered.mean()


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

@torch.no_grad()
def validate(model, tokenizer, val_samples: list[dict], device,
             max_samples: int = 200) -> float:
    """Compute validation accuracy."""
    model.eval()
    correct, total = 0, 0
    for obj in val_samples:
        if total >= max_samples:
            break
        prompt = build_prompt(obj["query"], obj.get("country", ""), tokenizer)
        enc = tokenizer(
            prompt, return_tensors="pt",
            max_length=MAX_PROMPT_LEN, truncation=True
        ).to(device)
        outs = model.generate(
            **enc, max_new_tokens=MAX_GEN_LEN,
            do_sample=False, temperature=None, top_p=None,
            pad_token_id=tokenizer.pad_token_id,
        )
        prompt_len = enc["input_ids"].shape[1]
        response = tokenizer.decode(outs[0][prompt_len:], skip_special_tokens=True)
        pred = extract_answer(response)
        if pred == str(obj["gt"]).strip():
            correct += 1
        total += 1
    model.train()
    return correct / total if total > 0 else 0.0


# ---------------------------------------------------------------------------
# Main training loop (LoRA, no DeepSpeed)
# ---------------------------------------------------------------------------

def train(args):
    policy_device = torch.device("cuda:0")
    prm_device = torch.device("cuda:1" if torch.cuda.device_count() > 1 else "cuda:0")

    model_path = MODEL_ALIASES.get(args.model_name, args.model_name)

    print(f"=" * 60)
    print(f"CAMA-D GRPO v3: LoRA Policy + disable_adapter Reference")
    print(f"=" * 60)
    print(f"Base model:    {model_path}")
    print(f"SFT adapter:   {args.sft_adapter or 'None (RL-only mode)'}")
    print(f"PRM path:      {args.prm_path}")
    print(f"Policy device: {policy_device}")
    print(f"PRM device:    {prm_device}")
    print(f"Alpha:         {args.alpha} "
          f"(R_total = {args.alpha}*R_outcome + {1-args.alpha:.1f}*Mean(R_process))")
    print(f"KL coef:       {KL_COEF}")
    print(f"LoRA rank:     {args.lora_r}")
    print(f"Eval every:    {args.eval_every} round(s)")

    # ---- Load data from pkl ----
    print(f"Loading data splits from: {args.data_pkl}")
    with open(args.data_pkl, "rb") as f:
        splits = pickle.load(f)
    train_data = splits["train"]
    val_data = splits["val"]
    print(f"  Data: train={len(train_data)}, val={len(val_data)}, "
          f"test={len(splits['test'])}")

    # ---- Tokenizer ----
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "left"

    # ---- Build Policy model ----
    # Step 1: Load base model
    base_model = AutoModelForCausalLM.from_pretrained(
        model_path, torch_dtype=torch.bfloat16, trust_remote_code=True
    )

    # Step 2: If SFT adapter exists, merge it into base (creates the SFT checkpoint in memory)
    if args.sft_adapter:
        print(f"  Merging SFT LoRA adapter: {args.sft_adapter}")
        base_model = PeftModel.from_pretrained(base_model, args.sft_adapter)
        base_model = base_model.merge_and_unload()
        print(f"  SFT adapter merged into base model (in memory)")

    # Step 3: Apply new GRPO LoRA on top of merged model
    lora_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        r=args.lora_r,
        lora_alpha=args.lora_alpha,
        lora_dropout=0.05,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                        "gate_proj", "up_proj", "down_proj"],
        bias="none",
    )
    policy = get_peft_model(base_model, lora_config).to(policy_device)
    policy.print_trainable_parameters()

    # Enable gradient checkpointing
    policy.enable_input_require_grads()
    policy.gradient_checkpointing_enable()

    # ---- Reference model: disable_adapter on the same model (zero extra memory) ----
    # When we call policy.disable_adapter_layers(), it acts as the reference.
    # No need to load a separate model!

    # ---- PRM v3 (frozen, on second GPU) ----
    # PRM backbone: base model + SFT-LoRA merged (matching PRM training conditions)
    prm_backbone = args.prm_backbone if args.prm_backbone else model_path
    prm = CulturePRM_v3(
        prm_checkpoint_dir=args.prm_path,
        backbone_path=prm_backbone,
        sft_adapter_path=args.sft_adapter,  # Merge SFT LoRA to match PRM training
    ).to(prm_device)
    prm_tokenizer = AutoTokenizer.from_pretrained(
        prm_backbone, trust_remote_code=True
    )
    if prm_tokenizer.pad_token is None:
        prm_tokenizer.pad_token = prm_tokenizer.eos_token
    for p in prm.parameters():
        p.requires_grad_(False)
    prm.eval()

    # ---- Optimizer (only GRPO LoRA params) ----
    trainable_params = [p for p in policy.parameters() if p.requires_grad]
    optimizer = torch.optim.AdamW(
        trainable_params, lr=args.lr, weight_decay=0.0, betas=(0.9, 0.95)
    )

    # ---- Dataset ----
    grpo_ds = GRPOPromptDataset(train_data)
    loader = DataLoader(grpo_ds, batch_size=args.prompt_batch, shuffle=True, pin_memory=False)

    Path(args.output_dir).mkdir(parents=True, exist_ok=True)
    best_val_acc = 0.0
    no_improve = 0

    print(f"GRPO prompts: {len(grpo_ds)} | "
          f"Rounds: {args.max_rounds} | n_samples: {args.n_samples}")
    print(f"Batches per round: {len(loader)} (prompt_batch={args.prompt_batch})")
    print(f"Starting training...")
    sys.stdout.flush()

    # ---- Training rounds ----
    for rnd in range(1, args.max_rounds + 1):
        round_loss = 0.0
        round_steps = 0
        round_r_outcome = 0.0
        round_r_process = 0.0
        round_r_total = 0.0
        round_n = 0

        for batch_idx, batch in enumerate(loader):
            queries = batch["query"]
            countries = batch["country"]
            golds = batch["gt"]
            n_prompts = len(queries)

            if batch_idx % 5 == 0:
                print(f"  Round {rnd} | Batch {batch_idx+1}/{len(loader)} | Generating {n_prompts}×{args.n_samples} samples...", flush=True)

            # 1. Build prompts
            prompts = [build_prompt(q, c, tokenizer)
                       for q, c in zip(queries, countries)]

            # 2. Generate n_samples responses per prompt (policy in eval mode)
            policy.eval()
            policy.gradient_checkpointing_disable()  # Allow use_cache during generation
            all_responses = generate_responses(
                policy, tokenizer, prompts,
                n_samples=args.n_samples,
                max_new_tokens=MAX_GEN_LEN,
                temperature=args.temperature,
                device=policy_device,
            )
            policy.gradient_checkpointing_enable()
            policy.train()

            # Free generation KV cache before policy gradient computation
            torch.cuda.empty_cache()

            if batch_idx % 5 == 0:
                print(f"  Round {rnd} | Batch {batch_idx+1}/{len(loader)} | Scoring with PRM...", flush=True)

            # 3. Compute rewards
            rewards = torch.zeros(n_prompts, args.n_samples, device=policy_device)
            scoring_count = 0

            for pi, (responses, gold, query, country) in enumerate(
                zip(all_responses, golds, queries, countries)
            ):
                for si, resp in enumerate(responses):
                    # R_outcome: binary correctness
                    pred = extract_answer(resp)
                    r_outcome = compute_r_outcome(pred, str(gold).strip())

                    # R_process: Mean(PRM step scores) — scored on prm_device
                    prm_input = build_prm_input(country, query, resp)
                    r_process = prm.score_reasoning(
                        prm_input, prm_tokenizer, prm_device
                    )
                    scoring_count += 1
                    if scoring_count % 10 == 0:
                        print(f"    Scored {scoring_count}/{n_prompts * args.n_samples}", flush=True)

                    # R_total = alpha * R_outcome + (1-alpha) * Mean(R_process)
                    r_total = args.alpha * r_outcome + (1 - args.alpha) * r_process
                    rewards[pi, si] = r_total

                    # Tracking
                    round_r_outcome += r_outcome
                    round_r_process += r_process
                    round_r_total += r_total
                    round_n += 1

            # 4. RLOO advantages
            advantages = rloo_advantages(rewards)

            # 5. Policy gradient with KL penalty
            # Two-phase approach:
            #   Phase A: compute all reference log-probs (eval mode, no grad)
            #   Phase B: per-sample policy forward+backward (train mode, with grad)
            total_samples = n_prompts * args.n_samples

            # Phase A: Reference log-probs (batch, no grad, no gradient checkpointing)
            policy.eval()
            ref_logprobs = {}  # (pi, si) -> float
            with torch.no_grad():
                with policy.disable_adapter():
                    for pi, (prompt, responses) in enumerate(zip(prompts, all_responses)):
                        for si, resp in enumerate(responses):
                            adv = advantages[pi, si].item()
                            if abs(adv) < 1e-8:
                                continue
                            lp_ref = compute_logprobs(
                                policy, tokenizer, prompt, resp, policy_device,
                                require_grad=False,
                            )
                            ref_logprobs[(pi, si)] = lp_ref.item()

            if batch_idx % 5 == 0:
                print(f"    Ref log-probs done ({len(ref_logprobs)} samples)", flush=True)

            # Phase B: Policy forward+backward (train mode, per-sample grad accumulation)
            policy.train()
            optimizer.zero_grad()
            loss_count = 0
            accumulated_loss = 0.0

            for pi, (prompt, responses) in enumerate(zip(prompts, all_responses)):
                for si, resp in enumerate(responses):
                    if (pi, si) not in ref_logprobs:
                        continue

                    adv = advantages[pi, si].item()
                    lp_ref_val = ref_logprobs[(pi, si)]

                    # Policy log-prob (with grad for backward)
                    lp_policy = compute_logprobs(
                        policy, tokenizer, prompt, resp, policy_device,
                        require_grad=True,
                    )

                    # KL penalty
                    lp_ref_t = torch.tensor(lp_ref_val, device=policy_device)
                    kl = (lp_policy - lp_ref_t).clamp(min=-10, max=10)
                    pg_loss = -(adv * lp_policy - KL_COEF * kl) / total_samples

                    # Backward immediately to free computation graph
                    pg_loss.backward()
                    accumulated_loss += pg_loss.item()
                    loss_count += 1

                    # Periodically log progress
                    if loss_count % 10 == 0:
                        print(f"    PG step {loss_count}/{len(ref_logprobs)}", flush=True)

            if loss_count > 0:
                torch.nn.utils.clip_grad_norm_(trainable_params, 1.0)
                optimizer.step()
                round_loss += accumulated_loss
                round_steps += 1

        # Round summary
        avg_loss = round_loss / max(round_steps, 1)
        avg_r_outcome = round_r_outcome / max(round_n, 1)
        avg_r_process = round_r_process / max(round_n, 1)
        avg_r_total = round_r_total / max(round_n, 1)

        print(f"Round {rnd}/{args.max_rounds} | "
              f"loss={avg_loss:.4f} | "
              f"R_outcome={avg_r_outcome:.3f} | "
              f"R_process={avg_r_process:.3f} | "
              f"R_total={avg_r_total:.3f}")

        # 6. Validation
        if rnd % args.eval_every == 0:
            val_acc = validate(
                policy, tokenizer, val_data, policy_device
            )
            print(f"  [Eval] Round {rnd} | val_accuracy={val_acc:.4f}")

            if val_acc > best_val_acc:
                best_val_acc = val_acc
                no_improve = 0
                ckpt = Path(args.output_dir) / "best"
                # Save only GRPO LoRA adapter
                policy.save_pretrained(str(ckpt))
                tokenizer.save_pretrained(str(ckpt))
                print(f"  ✓ Saved best GRPO LoRA (val_acc={best_val_acc:.4f}) → {ckpt}")
            else:
                no_improve += 1
                print(f"  No improvement ({no_improve}/3)")
                if no_improve >= 3:
                    print("Early stopping: val_accuracy not improving.")
                    break

    # If no eval was done, save final model
    if best_val_acc == 0.0:
        ckpt = Path(args.output_dir) / "best"
        policy.save_pretrained(str(ckpt))
        tokenizer.save_pretrained(str(ckpt))
        print(f"  Saved final GRPO LoRA (no eval performed) → {ckpt}")

    print(f"\nTraining complete. Best val_accuracy: {best_val_acc:.4f}")
    print(f"Best GRPO LoRA adapter: {args.output_dir}/best")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="CAMA-D Stage 3-GRPO: GRPO with Mean(R_process) — LoRA"
    )
    parser.add_argument("--model_name", type=str, required=True,
                        help="'llama', 'qwen', or full model path")
    parser.add_argument("--sft_adapter", type=str, default=None,
                        help="Stage 1 SFT LoRA adapter path (for SFT+RL mode). "
                             "Leave empty for RL-only mode.")
    parser.add_argument("--data_pkl", type=str, required=True,
                        help="Path to splits pkl file (from split_data.py)")
    parser.add_argument("--prm_path", type=str, required=True,
                        help="CAMA-D PRM checkpoint dir (LoRA + score_head.pt)")
    parser.add_argument("--prm_backbone", type=str, default=None,
                        help="PRM backbone model path. If not set, uses base model.")
    parser.add_argument("--output_dir", type=str, required=True,
                        help="Output directory for GRPO LoRA adapter")
    parser.add_argument("--alpha", type=float, default=DEFAULT_ALPHA,
                        help="R_outcome weight in R_total (default: 0.6)")
    parser.add_argument("--n_samples", type=int, default=10,
                        help="Responses per prompt per round (default: 10)")
    parser.add_argument("--temperature", type=float, default=0.7,
                        help="Sampling temperature (default: 0.7)")
    parser.add_argument("--max_rounds", type=int, default=30,
                        help="Maximum training rounds (default: 30)")
    parser.add_argument("--eval_every", type=int, default=5,
                        help="Evaluate every N rounds (default: 5)")
    parser.add_argument("--prompt_batch", type=int, default=4,
                        help="Prompts per optimizer step (default: 4)")
    parser.add_argument("--lr", type=float, default=5e-5,
                        help="Learning rate for GRPO LoRA (default: 5e-5, "
                             "use 2e-5 for SFT+RL)")
    parser.add_argument("--lora_r", type=int, default=16,
                        help="GRPO LoRA rank (default: 16)")
    parser.add_argument("--lora_alpha", type=int, default=32,
                        help="GRPO LoRA alpha (default: 32)")
    args = parser.parse_args()

    args.model_name = MODEL_ALIASES.get(args.model_name, args.model_name)
    train(args)


if __name__ == "__main__":
    main()
