"""
CGM-GRPO: Culture-Guided Mixed-Policy GRPO

Core innovation over standard GRPO (train_grpo_v3.py):
  - Guardian signal as advantage augmentation (NOT participating in RLOO baseline)
  - Three-factor cultural difficulty coefficient w_culture:
      w_culture = lambda1*(1-hit_rate) + lambda2*rarity_i + lambda3*(1-affinity_i)
  - Guardian quality-gated signal:
      S_guardian = R_outcome^guardian * (R_guardian - R_on_bar)
  - Similarity modulation:
      bonus_i = lambda * w_culture * S_guardian * Sim(y_i, y_guardian)
  - Final advantage: A_i = A_i^base + bonus_i
  - Guardian does NOT participate in policy gradient (no IS needed)

Key differences from train_grpo_v3.py:
  - w_culture is computed dynamically per prompt (not a fixed scalar)
  - Guardian R_guardian uses PRM scoring (alpha*R_outcome + (1-alpha)*Mean(R_process))
  - Two gate mechanisms: quality gate + necessity gate
  - Supports --w_culture_mode: "hit_only" / "hit_rarity" / "full"

Architecture (same as v3):
  - Policy: base model + SFT-LoRA merged + new GRPO-LoRA (trainable) on cuda:0
  - Reference: same model with adapter disabled (zero extra memory)
  - PRM: loaded on cuda:1 for parallel scoring

Hardware requirement: 2x vGPU-48GB

Usage:
    # MVP mode (w_culture = 1 - hit_rate only)
    python Cul/grpo/train_cgm_grpo.py \\
        --model_name     qwen \\
        --sft_adapter    /path/to/camad_sft_qwen/best \\
        --data_pkl       /path/to/normad_splits.pkl \\
        --prm_path       /path/to/camad_prm/best \\
        --guardian_data  /path/to/normad_hf_cac_inference.jsonl \\
        --output_dir     /path/to/models/camad_cgm_grpo_qwen \\
        --w_culture_mode hit_only \\
        --lambda_guide   0.5 \\
        --n_samples      5 \\
        --max_rounds     20 \\
        --eval_every     5

    # Full three-factor mode with affinity matrix
    python Cul/grpo/train_cgm_grpo.py \\
        --model_name     qwen \\
        --sft_adapter    /path/to/camad_sft_qwen/best \\
        --data_pkl       /path/to/normad_splits.pkl \\
        --prm_path       /path/to/camad_prm/best \\
        --guardian_data  /path/to/normad_hf_cac_inference.jsonl \\
        --affinity_config Cul/configs/hf_cac_config.yaml \\
        --output_dir     /path/to/models/camad_cgm_grpo_qwen \\
        --w_culture_mode full \\
        --lambda_guide   0.5 \\
        --alpha          0.6 \\
        --n_samples      5 \\
        --max_rounds     20 \\
        --batches_per_round 130 \\
        --eval_every     5

    The --data_pkl file should be generated by split_data.py (train/val/test splits).
"""

import re
import os
import json
import yaml
import pickle
import argparse
from pathlib import Path
from collections import defaultdict
from difflib import SequenceMatcher

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import LoraConfig, get_peft_model, PeftModel, TaskType

# Import step splitting utility
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from step_label.split_steps import split_reasoning_into_steps

# Reuse components from train_grpo_v3 (same directory)
from train_grpo_v3 import (
    CulturePRM_v3,
    GRPOPromptDataset,
    build_prompt,
    extract_answer,
    compute_r_outcome,
    build_prm_input,
    rloo_advantages,
    generate_responses,
    compute_logprobs,
    validate,
    load_guardian_index,
    compute_guardian_similarity,
)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MODEL_ALIASES = {
    "llama": "/root/autodl-tmp/base/Meta-Llama-3.1-8B-Instruct",
    "qwen":  "/root/autodl-tmp/base/Qwen2.5-7B-Instruct",
}

MAX_GEN_LEN = 128
MAX_PROMPT_LEN = 512
KL_COEF = 0.05
DEFAULT_ALPHA = 0.6
DEFAULT_LAMBDA_GUIDE = 0.5
NECESSITY_GATE_THRESHOLD = 0.8

# w_culture three-factor default weights
W_CULTURE_LAMBDA1 = 0.6   # (1 - hit_rate) weight
W_CULTURE_LAMBDA2 = 0.3   # rarity weight
W_CULTURE_LAMBDA3 = 0.1   # (1 - affinity) weight


# ---------------------------------------------------------------------------
# Country -> Culture Circle Mapping (6 circles from hf_cac_config.yaml)
# 0: Western, 1: Latin American, 2: Sub-Saharan African,
# 3: East-Asian, 4: Islamic & Middle-Eastern, 5: South & SE Asian
# ---------------------------------------------------------------------------

COUNTRY_TO_CIRCLE = {}

_CIRCLE_KEYWORDS = {
    0: ["united states", "usa", "america", "american", "canada", "australia",
        "new zealand", "uk", "united kingdom", "britain", "england", "scotland",
        "ireland", "france", "germany", "netherlands", "spain", "italy",
        "portugal", "sweden", "norway", "denmark", "finland", "poland",
        "greece", "austria", "switzerland", "belgium", "czech", "hungary",
        "romania", "ukraine", "russia", "croatia", "serbia", "bulgaria"],
    1: ["brazil", "mexico", "argentina", "chile", "colombia", "peru",
        "venezuela", "ecuador", "bolivia", "uruguay", "paraguay",
        "costa rica", "panama", "cuba", "dominican", "puerto rico",
        "guatemala", "honduras", "el salvador", "nicaragua"],
    2: ["nigeria", "kenya", "ethiopia", "ghana", "south africa", "tanzania",
        "uganda", "senegal", "cameroon", "ivory coast", "sudan", "congo",
        "angola", "mozambique", "zimbabwe", "zambia", "mali", "niger",
        "burkina faso", "somalia", "rwanda", "benin", "togo",
        "sierra leone", "liberia", "madagascar", "african"],
    3: ["china", "japan", "korea", "south korea", "taiwan", "mongolia"],
    4: ["arab", "arabic", "saudi", "iran", "iraq", "egypt", "turkey",
        "israel", "jordan", "lebanon", "uae", "qatar", "bahrain", "kuwait",
        "oman", "yemen", "syria", "palestine", "afghanistan", "morocco",
        "algeria", "tunisia", "libya"],
    5: ["india", "pakistan", "bangladesh", "nepal", "sri lanka", "thailand",
        "vietnam", "indonesia", "malaysia", "philippines", "singapore",
        "myanmar", "cambodia", "laos"],
}

for _circle_id, _keywords in _CIRCLE_KEYWORDS.items():
    for _kw in _keywords:
        COUNTRY_TO_CIRCLE[_kw] = _circle_id


def get_culture_circle(country: str) -> int:
    """Map a country string to its culture circle index (0-5). Returns -1 if unknown."""
    country_lower = country.lower().strip()
    if country_lower in COUNTRY_TO_CIRCLE:
        return COUNTRY_TO_CIRCLE[country_lower]
    for kw, cid in COUNTRY_TO_CIRCLE.items():
        if kw in country_lower or country_lower in kw:
            return cid
    return -1


# ---------------------------------------------------------------------------
# Cultural Difficulty Coefficient: w_culture
# ---------------------------------------------------------------------------

class CultureDifficultyComputer:
    """
    Computes the three-factor cultural difficulty coefficient w_culture.

    Modes:
      - "hit_only": w = 1 - hit_rate (MVP)
      - "hit_rarity": w = 0.67*(1-hit_rate) + 0.33*rarity_i
      - "full": w = 0.6*(1-hit_rate) + 0.3*rarity_i + 0.1*(1-affinity_i)
    """

    def __init__(self, mode: str, train_samples: list, affinity_config_path: str = None):
        self.mode = mode
        self.rarity_map = {}
        self.affinity_map = {}

        if mode in ("hit_rarity", "full"):
            self._compute_rarity(train_samples)

        if mode == "full":
            if affinity_config_path is None:
                raise ValueError("--affinity_config required for w_culture_mode='full'")
            self._load_affinity(affinity_config_path)

    def _compute_rarity(self, train_samples: list):
        """Compute rarity_i = 1 - freq_i for each culture circle."""
        circle_counts = defaultdict(int)
        total = 0
        for sample in train_samples:
            country = sample.get("country", "")
            circle = get_culture_circle(country)
            if circle >= 0:
                circle_counts[circle] += 1
                total += 1

        if total == 0:
            for i in range(6):
                self.rarity_map[i] = 0.5
            return

        for i in range(6):
            freq = circle_counts[i] / total
            self.rarity_map[i] = 1.0 - freq

        print(f"  [w_culture] Rarity stats (total={total}):")
        circle_names = ["Western", "Latin American", "Sub-Saharan African",
                        "East-Asian", "Islamic & Middle-Eastern", "South & SE Asian"]
        for i in range(6):
            freq = circle_counts[i] / total
            print(f"    {circle_names[i]}: count={circle_counts[i]}, "
                  f"freq={freq:.3f}, rarity={self.rarity_map[i]:.3f}")

    def _load_affinity(self, config_path: str):
        """Load affinity matrix and compute mean non-diagonal affinity per circle."""
        with open(config_path, "r", encoding="utf-8") as f:
            cfg = yaml.safe_load(f)

        matrix = cfg["cultural_affinity_matrix"]
        for i in range(6):
            row = matrix[i]
            non_diag = [row[j] for j in range(6) if j != i]
            self.affinity_map[i] = sum(non_diag) / len(non_diag)

        print(f"  [w_culture] Affinity map loaded from {config_path}")
        circle_names = ["Western", "Latin American", "Sub-Saharan African",
                        "East-Asian", "Islamic & Middle-Eastern", "South & SE Asian"]
        for i in range(6):
            print(f"    {circle_names[i]}: mean_affinity={self.affinity_map[i]:.3f}, "
                  f"(1-affinity)={1-self.affinity_map[i]:.3f}")

    def compute(self, hit_rate: float, country: str) -> float:
        """Compute w_culture for a given prompt."""
        if self.mode == "hit_only":
            return 1.0 - hit_rate

        circle = get_culture_circle(country)

        if self.mode == "hit_rarity":
            rarity = self.rarity_map.get(circle, 0.5)
            return 0.67 * (1.0 - hit_rate) + 0.33 * rarity

        # full mode
        rarity = self.rarity_map.get(circle, 0.5)
        affinity = self.affinity_map.get(circle, 0.3)
        return (W_CULTURE_LAMBDA1 * (1.0 - hit_rate) +
                W_CULTURE_LAMBDA2 * rarity +
                W_CULTURE_LAMBDA3 * (1.0 - affinity))


# ---------------------------------------------------------------------------
# CGM-GRPO: Guardian Advantage with PRM Scoring
# ---------------------------------------------------------------------------

def compute_guardian_r_total(
    guardian_text: str,
    guardian_answer: str,
    gold: str,
    country: str,
    query: str,
    prm,
    prm_tokenizer,
    prm_device,
    alpha: float,
):
    """
    Compute R_guardian = alpha * R_outcome_guardian + (1-alpha) * Mean(R_process_guardian).
    Returns (r_guardian, r_outcome_guardian).
    """
    r_outcome_guardian = compute_r_outcome(guardian_answer, gold)

    if prm is None:
        return r_outcome_guardian, r_outcome_guardian

    prm_input = build_prm_input(country, query, guardian_text)
    r_process_guardian = prm.score_reasoning(prm_input, prm_tokenizer, prm_device)

    r_guardian = alpha * r_outcome_guardian + (1.0 - alpha) * r_process_guardian
    return r_guardian, r_outcome_guardian


def compute_cgm_advantage_bonus(
    queries, countries, golds, all_responses, r_outcomes_flat,
    guardian_index, lambda_guide, w_culture_computer, sim_mode,
    n_samples, prm, prm_tokenizer, prm_device, alpha, device,
    hit_rate_threshold=0.8,
):
    """
    Compute the CGM-GRPO advantage bonus for a batch.

    Formula: bonus[pi, si] = lambda * w_culture * S_guardian * Sim(y_i, y_guardian)
    Gates: quality gate (Guardian correct) + necessity gate (hit_rate < threshold)

    Returns (bonus_tensor, stats_dict).
    """
    n_prompts = len(queries)
    bonus = torch.zeros(n_prompts, n_samples, device=device)

    stats = {
        "guardian_found": 0,
        "guardian_correct": 0,
        "guardian_skipped_quality": 0,
        "guardian_skipped_necessity": 0,
        "mean_w_culture": 0.0,
        "mean_s_guardian": 0.0,
    }

    w_culture_sum = 0.0
    s_guardian_sum = 0.0
    active_count = 0

    for pi in range(n_prompts):
        country = countries[pi]
        query = queries[pi]
        gold = str(golds[pi]).strip()

        key = (country.lower().strip(), query[:200].lower().strip())
        guardian_data = guardian_index.get(key, None)

        if guardian_data is None:
            continue

        stats["guardian_found"] += 1
        guardian_answer = guardian_data["guardian_answer"]
        guardian_response = guardian_data["guardian_response"]

        if guardian_answer is None:
            continue

        # Compute hit_rate for this prompt
        start_idx = pi * n_samples
        prompt_r_outcomes = r_outcomes_flat[start_idx:start_idx + n_samples]
        hit_rate = sum(1.0 for r in prompt_r_outcomes if r > 0.5) / max(n_samples, 1)

        # Necessity gate
        if hit_rate >= hit_rate_threshold:
            stats["guardian_skipped_necessity"] += 1
            continue

        # Compute R_guardian (with PRM scoring)
        r_guardian, r_outcome_guardian = compute_guardian_r_total(
            guardian_text=guardian_response,
            guardian_answer=guardian_answer,
            gold=gold,
            country=country,
            query=query,
            prm=prm,
            prm_tokenizer=prm_tokenizer,
            prm_device=prm_device,
            alpha=alpha,
        )

        # Quality gate
        if r_outcome_guardian < 0.5:
            stats["guardian_skipped_quality"] += 1
            continue

        stats["guardian_correct"] += 1

        # R_on_bar_full (full group mean)
        mean_r_on = sum(prompt_r_outcomes) / max(len(prompt_r_outcomes), 1)

        # S_guardian = R_outcome^guardian * (R_guardian - R_on_bar_full)
        s_guardian = r_outcome_guardian * (r_guardian - mean_r_on)

        # w_culture
        w_culture = w_culture_computer.compute(hit_rate, country)

        w_culture_sum += w_culture
        s_guardian_sum += abs(s_guardian)
        active_count += 1

        if abs(s_guardian) < 1e-8:
            continue

        # Similarity modulation per rollout
        for si, resp in enumerate(all_responses[pi]):
            sim = compute_guardian_similarity(resp, guardian_data, sim_mode)
            bonus[pi, si] = lambda_guide * w_culture * s_guardian * sim

    if active_count > 0:
        stats["mean_w_culture"] = w_culture_sum / active_count
        stats["mean_s_guardian"] = s_guardian_sum / active_count

    return bonus, stats


# ---------------------------------------------------------------------------
# Main training loop
# ---------------------------------------------------------------------------

def train(args):
    if not args.no_prm and args.prm_path is None:
        raise ValueError("--prm_path is required when PRM scoring is enabled.")

    if args.guardian_data is None:
        raise ValueError("--guardian_data is required for CGM-GRPO. "
                         "Use train_grpo_v3.py for standard GRPO.")

    policy_device = torch.device("cuda:0")
    prm_device = torch.device("cuda:1" if torch.cuda.device_count() > 1 else "cuda:0")

    model_path = MODEL_ALIASES.get(args.model_name, args.model_name)

    # ---- Load Guardian index ----
    guardian_index = load_guardian_index(args.guardian_data)

    print(f"{'=' * 60}")
    print(f"CGM-GRPO: Culture-Guided Mixed-Policy GRPO")
    print(f"{'=' * 60}")
    print(f"Base model:      {model_path}")
    print(f"SFT adapter:     {args.sft_adapter or 'None (RL-only)'}")
    print(f"PRM path:        {args.prm_path}")
    print(f"Policy device:   {policy_device}")
    print(f"PRM device:      {prm_device}")
    print(f"Alpha:           {args.alpha}")
    print(f"KL coef:         {KL_COEF}")
    print(f"Lambda guide:    {args.lambda_guide}")
    print(f"w_culture mode:  {args.w_culture_mode}")
    print(f"Sim mode:        {args.guardian_sim_mode}")
    print(f"Necessity gate:  hit_rate >= {args.hit_rate_threshold}")
    print(f"LoRA rank:       {args.lora_r}")
    print(f"Eval every:      {args.eval_every} round(s)")

    # ---- Load data ----
    print(f"Loading data splits from: {args.data_pkl}")
    with open(args.data_pkl, "rb") as f:
        splits = pickle.load(f)
    train_data = splits["train"]
    val_data = splits["val"]
    print(f"  Data: train={len(train_data)}, val={len(val_data)}, "
          f"test={len(splits['test'])}")

    # ---- Initialize w_culture computer ----
    w_culture_computer = CultureDifficultyComputer(
        mode=args.w_culture_mode,
        train_samples=train_data,
        affinity_config_path=args.affinity_config,
    )

    # ---- Tokenizer ----
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "left"

    # ---- Build Policy model ----
    base_model = AutoModelForCausalLM.from_pretrained(
        model_path, torch_dtype=torch.bfloat16, trust_remote_code=True
    )

    if args.sft_adapter:
        print(f"  Merging SFT LoRA adapter: {args.sft_adapter}")
        base_model = PeftModel.from_pretrained(base_model, args.sft_adapter)
        base_model = base_model.merge_and_unload()
        print(f"  SFT adapter merged into base model")

    lora_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        r=args.lora_r,
        lora_alpha=args.lora_alpha,
        lora_dropout=0.05,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                        "gate_proj", "up_proj", "down_proj"],
        bias="none",
    )
    policy = get_peft_model(base_model, lora_config).to(policy_device)
    policy.print_trainable_parameters()
    policy.enable_input_require_grads()
    policy.gradient_checkpointing_enable()

    # ---- PRM (frozen, on second GPU) ----
    if not args.no_prm:
        prm_backbone = args.prm_backbone if args.prm_backbone else model_path
        prm = CulturePRM_v3(
            prm_checkpoint_dir=args.prm_path,
            backbone_path=prm_backbone,
            sft_adapter_path=args.sft_adapter,
        ).to(prm_device)
        prm_tokenizer = AutoTokenizer.from_pretrained(
            prm_backbone, trust_remote_code=True
        )
        if prm_tokenizer.pad_token is None:
            prm_tokenizer.pad_token = prm_tokenizer.eos_token
        for p in prm.parameters():
            p.requires_grad_(False)
        prm.eval()
    else:
        prm = None
        prm_tokenizer = None
        print("  [PRM] Skipped (--no_prm mode)")

    # ---- Optimizer ----
    trainable_params = [p for p in policy.parameters() if p.requires_grad]
    optimizer = torch.optim.AdamW(
        trainable_params, lr=args.lr, weight_decay=0.0, betas=(0.9, 0.95)
    )

    # ---- Dataset ----
    grpo_ds = GRPOPromptDataset(train_data)
    loader = DataLoader(grpo_ds, batch_size=args.prompt_batch,
                        shuffle=True, pin_memory=False)

    Path(args.output_dir).mkdir(parents=True, exist_ok=True)
    best_val_acc = 0.0
    no_improve = 0

    effective_batches_info = (
        f"all {len(loader)}" if args.batches_per_round < 0
        else f"{min(args.batches_per_round, len(loader))}/{len(loader)}"
    )
    print(f"CGM-GRPO prompts: {len(grpo_ds)} | "
          f"Rounds: {args.max_rounds} | n_samples: {args.n_samples}")
    print(f"Batches per round: {effective_batches_info}")
    print(f"PRM scoring: {'DISABLED' if args.no_prm else 'ENABLED'}")
    print(f"Starting training...")
    sys.stdout.flush()

    # ---- Training rounds ----
    for rnd in range(1, args.max_rounds + 1):
        round_loss = 0.0
        round_steps = 0
        round_r_outcome = 0.0
        round_r_process = 0.0
        round_r_total = 0.0
        round_cgm_bonus = 0.0
        round_w_culture = 0.0
        round_s_guardian = 0.0
        round_guardian_found = 0
        round_guardian_correct = 0
        round_n = 0
        round_cgm_batches = 0

        effective_batches = (len(loader) if args.batches_per_round < 0
                            else min(args.batches_per_round, len(loader)))

        for batch_idx, batch in enumerate(loader):
            if batch_idx >= effective_batches:
                break

            queries = batch["query"]
            countries = batch["country"]
            golds = batch["gt"]
            n_prompts = len(queries)

            if batch_idx % 5 == 0:
                print(f"  Round {rnd} | Batch {batch_idx+1}/{effective_batches} | "
                      f"Gen {n_prompts}x{args.n_samples}...", flush=True)

            # 1. Build prompts
            prompts = [build_prompt(q, c, tokenizer)
                       for q, c in zip(queries, countries)]

            # 2. Generate on-policy responses
            policy.eval()
            policy.gradient_checkpointing_disable()
            all_responses = generate_responses(
                policy, tokenizer, prompts,
                n_samples=args.n_samples,
                max_new_tokens=MAX_GEN_LEN,
                temperature=args.temperature,
                device=policy_device,
            )
            policy.gradient_checkpointing_enable()
            policy.train()
            torch.cuda.empty_cache()

            # 3. Compute rewards
            rewards = torch.zeros(n_prompts, args.n_samples, device=policy_device)
            r_outcomes = []

            for pi, (responses, gold) in enumerate(zip(all_responses, golds)):
                for si, resp in enumerate(responses):
                    pred = extract_answer(resp)
                    r_outcomes.append(compute_r_outcome(pred, str(gold).strip()))

            if args.no_prm:
                r_processes = [0.0] * (n_prompts * args.n_samples)
            else:
                prm_inputs = []
                for pi, (responses, query, country) in enumerate(
                    zip(all_responses, queries, countries)
                ):
                    for si, resp in enumerate(responses):
                        prm_inputs.append(build_prm_input(country, query, resp))

                PRM_BATCH_SIZE = 20
                r_processes = []
                for i in range(0, len(prm_inputs), PRM_BATCH_SIZE):
                    batch_texts = prm_inputs[i:i + PRM_BATCH_SIZE]
                    batch_scores = prm.score_batch(
                        batch_texts, prm_tokenizer, prm_device, max_len=512
                    )
                    r_processes.extend(batch_scores)

            idx = 0
            for pi in range(n_prompts):
                for si in range(args.n_samples):
                    r_outcome = r_outcomes[idx]
                    r_process = r_processes[idx]
                    if args.no_prm:
                        r_total = r_outcome
                    else:
                        r_total = (args.alpha * r_outcome +
                                   (1 - args.alpha) * r_process)
                    rewards[pi, si] = r_total
                    round_r_outcome += r_outcome
                    round_r_process += r_process
                    round_r_total += r_total
                    round_n += 1
                    idx += 1

            # 4. RLOO advantages (base)
            advantages = rloo_advantages(rewards)

            # 4b. CGM-GRPO advantage bonus
            cgm_bonus, cgm_stats = compute_cgm_advantage_bonus(
                queries=queries,
                countries=countries,
                golds=golds,
                all_responses=all_responses,
                r_outcomes_flat=r_outcomes,
                guardian_index=guardian_index,
                lambda_guide=args.lambda_guide,
                w_culture_computer=w_culture_computer,
                sim_mode=args.guardian_sim_mode,
                n_samples=args.n_samples,
                prm=prm,
                prm_tokenizer=prm_tokenizer,
                prm_device=prm_device,
                alpha=args.alpha,
                device=policy_device,
                hit_rate_threshold=args.hit_rate_threshold,
            )
            advantages = advantages + cgm_bonus
            round_cgm_bonus += cgm_bonus.abs().mean().item()
            round_w_culture += cgm_stats["mean_w_culture"]
            round_s_guardian += cgm_stats["mean_s_guardian"]
            round_guardian_found += cgm_stats["guardian_found"]
            round_guardian_correct += cgm_stats["guardian_correct"]
            round_cgm_batches += 1

            # 5. Policy gradient with KL penalty
            total_samples = n_prompts * args.n_samples

            # Phase A: Reference log-probs
            policy.eval()
            policy.gradient_checkpointing_disable()
            ref_logprobs = {}
            with torch.no_grad():
                with policy.disable_adapter():
                    for pi, (prompt, responses) in enumerate(
                        zip(prompts, all_responses)
                    ):
                        for si, resp in enumerate(responses):
                            adv = advantages[pi, si].item()
                            if abs(adv) < 1e-8:
                                continue
                            lp_ref = compute_logprobs(
                                policy, tokenizer, prompt, resp,
                                policy_device, require_grad=False,
                            )
                            ref_logprobs[(pi, si)] = lp_ref.item()

            # Phase B: Policy forward+backward
            policy.gradient_checkpointing_enable()
            policy.train()
            optimizer.zero_grad()
            loss_count = 0
            accumulated_loss = 0.0

            for pi, (prompt, responses) in enumerate(zip(prompts, all_responses)):
                for si, resp in enumerate(responses):
                    if (pi, si) not in ref_logprobs:
                        continue

                    adv = advantages[pi, si].item()
                    lp_ref_val = ref_logprobs[(pi, si)]

                    lp_policy = compute_logprobs(
                        policy, tokenizer, prompt, resp,
                        policy_device, require_grad=True,
                    )

                    lp_ref_t = torch.tensor(lp_ref_val, device=policy_device)
                    kl = (lp_policy - lp_ref_t).clamp(min=-10, max=10)
                    pg_loss = -(adv * lp_policy - KL_COEF * kl) / total_samples

                    pg_loss.backward()
                    accumulated_loss += pg_loss.item()
                    loss_count += 1

                    if loss_count % 10 == 0:
                        print(f"    PG step {loss_count}/{len(ref_logprobs)}",
                              flush=True)

            if loss_count > 0:
                torch.nn.utils.clip_grad_norm_(trainable_params, 1.0)
                optimizer.step()
                round_loss += accumulated_loss
                round_steps += 1

        # Round summary
        avg_loss = round_loss / max(round_steps, 1)
        avg_r_outcome = round_r_outcome / max(round_n, 1)
        avg_r_process = round_r_process / max(round_n, 1)
        avg_r_total = round_r_total / max(round_n, 1)
        avg_cgm = round_cgm_bonus / max(round_cgm_batches, 1)
        avg_wc = round_w_culture / max(round_cgm_batches, 1)
        avg_sg = round_s_guardian / max(round_cgm_batches, 1)

        print(f"Round {rnd}/{args.max_rounds} | "
              f"loss={avg_loss:.4f} | "
              f"R_out={avg_r_outcome:.3f} | "
              f"R_proc={avg_r_process:.3f} | "
              f"R_total={avg_r_total:.3f}")
        print(f"  CGM: bonus={avg_cgm:.4f} | "
              f"w_culture={avg_wc:.3f} | "
              f"S_guard={avg_sg:.3f} | "
              f"G_found={round_guardian_found} | "
              f"G_correct={round_guardian_correct}")

        # 6. Validation
        if rnd % args.eval_every == 0:
            val_acc = validate(policy, tokenizer, val_data, policy_device)
            print(f"  [Eval] Round {rnd} | val_accuracy={val_acc:.4f}")

            if val_acc > best_val_acc:
                best_val_acc = val_acc
                no_improve = 0
                ckpt = Path(args.output_dir) / "best"
                policy.save_pretrained(str(ckpt))
                tokenizer.save_pretrained(str(ckpt))
                print(f"  Saved best CGM-GRPO LoRA "
                      f"(val_acc={best_val_acc:.4f}) -> {ckpt}")
            else:
                no_improve += 1
                print(f"  No improvement ({no_improve}/3)")
                if no_improve >= 3:
                    print("Early stopping.")
                    break

    if best_val_acc == 0.0:
        ckpt = Path(args.output_dir) / "best"
        policy.save_pretrained(str(ckpt))
        tokenizer.save_pretrained(str(ckpt))
        print(f"  Saved final CGM-GRPO LoRA -> {ckpt}")

    print(f"\nTraining complete. Best val_accuracy: {best_val_acc:.4f}")
    print(f"Best CGM-GRPO LoRA adapter: {args.output_dir}/best")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="CAMA-D CGM-GRPO: Culture-Guided Mixed-Policy GRPO"
    )
    parser.add_argument("--model_name", type=str, required=True)
    parser.add_argument("--sft_adapter", type=str, default=None)
    parser.add_argument("--data_pkl", type=str, required=True)
    parser.add_argument("--prm_path", type=str, default=None)
    parser.add_argument("--prm_backbone", type=str, default=None)
    parser.add_argument("--output_dir", type=str, required=True)
    parser.add_argument("--alpha", type=float, default=DEFAULT_ALPHA)
    parser.add_argument("--n_samples", type=int, default=5)
    parser.add_argument("--temperature", type=float, default=0.7)
    parser.add_argument("--max_rounds", type=int, default=30)
    parser.add_argument("--eval_every", type=int, default=5)
    parser.add_argument("--prompt_batch", type=int, default=8)
    parser.add_argument("--lr", type=float, default=5e-5)
    parser.add_argument("--lora_r", type=int, default=16)
    parser.add_argument("--lora_alpha", type=int, default=32)
    parser.add_argument("--batches_per_round", type=int, default=130)
    parser.add_argument("--no_prm", action="store_true")
    # CGM-GRPO specific
    parser.add_argument("--guardian_data", type=str, default=None,
                        help="HF-CAC inference JSONL with Guardian responses.")
    parser.add_argument("--lambda_guide", type=float, default=DEFAULT_LAMBDA_GUIDE,
                        help="Guardian guidance strength (default: 0.5).")
    parser.add_argument("--w_culture_mode", type=str, default="hit_rarity",
                        choices=["hit_only", "hit_rarity", "full"],
                        help="w_culture mode (default: hit_rarity).")
    parser.add_argument("--affinity_config", type=str, default=None,
                        help="hf_cac_config.yaml path (for full mode).")
    parser.add_argument("--guardian_sim_mode", type=str, default="answer",
                        choices=["answer", "step_overlap", "hybrid"],
                        help="Similarity mode (default: answer).")
    parser.add_argument("--hit_rate_threshold", type=float, default=0.8,
                        help="Necessity gate threshold (default: 0.8).")
    args = parser.parse_args()

    args.model_name = MODEL_ALIASES.get(args.model_name, args.model_name)
    train(args)


if __name__ == "__main__":
    main()
