"""
AgentArk Baseline — Stage 1: Standard SFT (Uniform Loss)

Key differences from CAMA-D:
  - NO token weighting (all agent outputs have equal loss weight)
  - NO role-span extraction (no Guardian/Auditor hierarchy)
  - Uniform cross-entropy loss over the entire response
  - Same LoRA fine-tuning approach for fair comparison

Training data: multi-agent debate output (from generate_debate_data.py)
  Format: each sample has response with ===== Solution N [AGENT-X] ===== markers.
  We use the full response (all agents + judge) as the SFT target.

Input format:  {question}
Output format: The full multi-agent debate output (all solutions concatenated)

Supports multi-GPU DDP training via HuggingFace Accelerate.

Usage (single GPU):
    python ark/culture/train_sft.py \\
        --model_name  qwen \\
        --data_pkl    /path/to/normad_agentark_splits.pkl \\
        --output_dir  /path/to/models/agentark_sft_qwen \\
        --epochs      3 \\
        --batch_size  4 \\
        --lr          2e-4 \\
        --lora_r      32

Usage (multi-GPU DDP via accelerate):
    accelerate launch --num_processes 2 ark/culture/train_sft.py \\
        --model_name  qwen \\
        --data_pkl    /path/to/normad_agentark_splits.pkl \\
        --output_dir  /path/to/models/agentark_sft_qwen \\
        --epochs      5 \\
        --batch_size  4 \\
        --lr          2e-4

    The --data_pkl file should be generated by split_data.py (contains train/val/test splits).
"""

import re
import json
import argparse
import pickle
from pathlib import Path
from typing import Optional

import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    get_cosine_schedule_with_warmup,
)
from peft import LoraConfig, get_peft_model, TaskType
from datetime import timedelta
from accelerate import Accelerator, InitProcessGroupKwargs
from accelerate.utils import set_seed


MODEL_ALIASES = {
    "llama": "/root/autodl-tmp/base/Meta-Llama-3.1-8B-Instruct",
    "qwen":  "/root/autodl-tmp/base/Qwen2.5-7B-Instruct",
}

MAX_SEQ_LEN = 2048
IGNORE_INDEX = -100


# ---------------------------------------------------------------------------
# Data processing: AgentArk debate output → SFT samples
# ---------------------------------------------------------------------------

def extract_judge_answer(response: str, max_choice: int = 3) -> Optional[str]:
    """Extract Judge's final answer from debate output."""
    judge_match = re.search(
        r'===== Solution \d+ \[JUDGE\] =====\n(.*?)$',
        response, re.DOTALL
    )
    if not judge_match:
        # Try without [JUDGE] tag (alternative format)
        judge_match = re.search(
            r'===== Solution \d+ =====\n(.*?)$',
            response, re.DOTALL
        )
    if not judge_match:
        return None
    judge_text = judge_match.group(1)
    m = re.search(rf'Answer\s*:\s*([1-{max_choice}])', judge_text, re.IGNORECASE)
    if m:
        return m.group(1)
    digits = re.findall(rf'\b([1-{max_choice}])\b', judge_text)
    return digits[-1] if digits else None


def build_agentark_sft_samples(samples_raw: list[dict]) -> list[dict]:
    """
    Build SFT training samples from AgentArk debate inference data.

    Filtering: only include samples where the Judge's answer matches
    the ground truth (correct debate outcomes only).

    Each sample:
      - query: the cultural question
      - country: target country
      - response: full multi-agent debate output (used as SFT target)
      - gt: ground truth answer
    """
    samples = []
    skipped = 0

    for obj in samples_raw:
        query = obj.get("query", "")
        country = obj.get("country", "")
        gold = str(obj.get("gt", "")).strip()
        response = obj.get("response", "")

        if not response or not gold:
            skipped += 1
            continue

        # Determine max_choice based on dataset type
        dataset_type = obj.get("dataset_type", "normad")
        max_choice = 4 if dataset_type == "culturalbench" else 3

        # Filter: only keep samples where Judge is correct
        judge_ans = extract_judge_answer(response, max_choice)
        if judge_ans != gold:
            skipped += 1
            continue

        samples.append({
            "query": query,
            "country": country,
            "response": response,
            "gt": gold,
        })

    print(f"AgentArk SFT samples: {len(samples)} valid, {skipped} skipped "
          f"(incorrect/invalid)")
    return samples


# ---------------------------------------------------------------------------
# Dataset: Standard SFT (uniform loss, no weighting)
# ---------------------------------------------------------------------------

class StandardSFTDataset(Dataset):
    """
    Standard SFT dataset: uniform cross-entropy loss over response tokens.

    No token weighting — this is the AgentArk baseline approach.
    All agent outputs (AGENT-1, AGENT-2, ..., JUDGE) receive equal loss.
    """

    def __init__(self, samples: list[dict], tokenizer, max_len: int = MAX_SEQ_LEN):
        self.tokenizer = tokenizer
        self.max_len = max_len
        self.records = []

        for s in samples:
            # Input: question only (no country conditioning in AgentArk)
            # AgentArk does NOT use cultural identity — just the raw question
            input_text = s["query"]
            target_text = s["response"]

            messages = [
                {"role": "user", "content": input_text},
                {"role": "assistant", "content": target_text},
            ]
            full_text = tokenizer.apply_chat_template(
                messages, tokenize=False, add_generation_prompt=False
            )
            prompt_only = tokenizer.apply_chat_template(
                [{"role": "user", "content": input_text}],
                tokenize=False, add_generation_prompt=True,
            )
            self.records.append((full_text, prompt_only))

    def __len__(self):
        return len(self.records)

    def __getitem__(self, idx):
        full_text, prompt_text = self.records[idx]
        tok = self.tokenizer

        full_enc = tok(
            full_text, max_length=self.max_len,
            truncation=True, return_tensors="pt",
        )
        prompt_enc = tok(
            prompt_text, max_length=self.max_len,
            truncation=True, return_tensors="pt",
        )

        input_ids = full_enc["input_ids"].squeeze(0)
        attention_mask = full_enc["attention_mask"].squeeze(0)
        prompt_len = prompt_enc["input_ids"].shape[1]

        # Standard labels: mask prompt tokens, uniform loss on response
        labels = input_ids.clone()
        labels[:prompt_len] = IGNORE_INDEX

        return {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
            "labels": labels,
        }


def collate_fn(batch: list[dict]) -> dict:
    """Pad sequences to max length in batch."""
    max_len = max(b["input_ids"].shape[0] for b in batch)
    pad_id = 0

    input_ids_list, mask_list, label_list = [], [], []

    for b in batch:
        n = b["input_ids"].shape[0]
        pad = max_len - n

        input_ids_list.append(
            torch.cat([b["input_ids"], torch.full((pad,), pad_id, dtype=torch.long)])
        )
        mask_list.append(
            torch.cat([b["attention_mask"], torch.zeros(pad, dtype=torch.long)])
        )
        label_list.append(
            torch.cat([b["labels"], torch.full((pad,), IGNORE_INDEX, dtype=torch.long)])
        )

    return {
        "input_ids": torch.stack(input_ids_list),
        "attention_mask": torch.stack(mask_list),
        "labels": torch.stack(label_list),
    }


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

@torch.no_grad()
def validate(model, tokenizer, val_samples: list[dict], accelerator: Accelerator,
             max_samples: int = 200) -> float:
    """Compute accuracy on validation set. Only on main process."""
    unwrapped_model = accelerator.unwrap_model(model)
    unwrapped_model.eval()

    # Disable gradient checkpointing during generation
    if hasattr(unwrapped_model, "base_model"):
        underlying = (unwrapped_model.base_model.model
                      if hasattr(unwrapped_model.base_model, "model")
                      else unwrapped_model.base_model)
    else:
        underlying = unwrapped_model
    underlying.gradient_checkpointing_disable()
    underlying.config.use_cache = True

    device = accelerator.device
    correct, total = 0, 0

    for obj in val_samples:
        if total >= max_samples:
            break
        query = obj["query"]
        gold = str(obj["gt"]).strip()

        # AgentArk: no country prefix in prompt
        messages = [{"role": "user", "content": query}]
        prompt = tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        enc = tokenizer(
            prompt, return_tensors="pt",
            max_length=MAX_SEQ_LEN, truncation=True
        ).to(device)

        outs = unwrapped_model.generate(
            **enc,
            max_new_tokens=128,
            do_sample=False,
            top_k=None, top_p=None, temperature=None,
            pad_token_id=tokenizer.pad_token_id,
            use_cache=True,
        )
        prompt_len = enc["input_ids"].shape[1]
        response = tokenizer.decode(outs[0][prompt_len:], skip_special_tokens=True)

        pred = None
        m = re.search(r"Answer\s*:\s*([1-4])", response, re.IGNORECASE)
        if m:
            pred = m.group(1)
        else:
            digits = re.findall(r"\b([1-4])\b", response)
            if digits:
                pred = digits[-1]

        if pred == gold:
            correct += 1
        total += 1

        if total % 50 == 0:
            accelerator.print(f"    Eval progress: {total}/{max_samples} "
                              f"(acc so far: {correct/total:.3f})")

    # Re-enable gradient checkpointing for training
    underlying.config.use_cache = False
    underlying.gradient_checkpointing_enable()
    unwrapped_model.train()
    acc = correct / total if total > 0 else 0.0
    return acc


# ---------------------------------------------------------------------------
# Training (LoRA + Accelerate DDP)
# ---------------------------------------------------------------------------

def train(args):
    # Initialize Accelerator
    ddp_kwargs = InitProcessGroupKwargs(timeout=timedelta(minutes=30))
    accelerator = Accelerator(
        gradient_accumulation_steps=args.grad_accum_steps,
        mixed_precision="bf16",
        kwargs_handlers=[ddp_kwargs],
    )
    set_seed(42)

    accelerator.print(f"{'='*60}")
    accelerator.print(f"AgentArk Baseline — Stage 1: Standard SFT (Uniform Loss)")
    accelerator.print(f"{'='*60}")
    accelerator.print(f"Number of processes: {accelerator.num_processes}")
    accelerator.print(f"Device: {accelerator.device}")
    accelerator.print(f"Loss weighting: UNIFORM (no role-based weighting)")
    accelerator.print(f"LoRA rank: {args.lora_r}, LoRA alpha: {args.lora_alpha}")
    accelerator.print(f"Eval every {args.eval_every_n_epochs} epoch(s)")

    model_path = MODEL_ALIASES[args.model_name]
    accelerator.print(f"Base model: {model_path}")

    # Load data from pkl
    accelerator.print(f"Loading data splits from: {args.data_pkl}")
    with open(args.data_pkl, "rb") as f:
        splits = pickle.load(f)
    train_raw = splits["train"]
    val_raw = splits["val"]
    accelerator.print(f"  Raw data: train={len(train_raw)}, val={len(val_raw)}, "
                      f"test={len(splits['test'])}")

    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    # Load base model
    base_model = AutoModelForCausalLM.from_pretrained(
        model_path, torch_dtype=torch.bfloat16, trust_remote_code=True
    )

    # Apply LoRA
    lora_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        r=args.lora_r,
        lora_alpha=args.lora_alpha,
        lora_dropout=0.05,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                        "gate_proj", "up_proj", "down_proj"],
        bias="none",
    )
    model = get_peft_model(base_model, lora_config)
    if accelerator.is_main_process:
        model.print_trainable_parameters()

    # Enable gradient checkpointing
    model.enable_input_require_grads()
    model.gradient_checkpointing_enable()

    # Build SFT samples from debate data
    train_samples = build_agentark_sft_samples(train_raw)
    if len(train_samples) == 0:
        raise ValueError("No valid SFT samples found. Check data format.")

    if args.max_samples > 0:
        train_samples = train_samples[:args.max_samples]
        accelerator.print(f"Using first {args.max_samples} training samples")
    else:
        accelerator.print(f"Using all {len(train_samples)} training samples")

    train_ds = StandardSFTDataset(train_samples, tokenizer)
    loader = DataLoader(
        train_ds,
        batch_size=args.batch_size,
        shuffle=True,
        collate_fn=collate_fn,
        num_workers=2,
        pin_memory=True,
    )
    accelerator.print(f"Training batches per epoch (per device): {len(loader)}")

    # Optimizer
    trainable_params = [p for p in model.parameters() if p.requires_grad]
    optimizer = torch.optim.AdamW(
        trainable_params, lr=args.lr, weight_decay=0.01
    )
    total_steps = (len(loader) * args.epochs) // args.grad_accum_steps
    warmup_steps = max(1, int(total_steps * 0.05))
    scheduler = get_cosine_schedule_with_warmup(
        optimizer, warmup_steps, total_steps
    )

    # Prepare with accelerator
    model, optimizer, loader, scheduler = accelerator.prepare(
        model, optimizer, loader, scheduler
    )

    Path(args.output_dir).mkdir(parents=True, exist_ok=True)
    best_val_acc = 0.0

    for epoch in range(1, args.epochs + 1):
        model.train()
        total_loss = 0.0
        num_steps = 0

        for step, batch in enumerate(loader, 1):
            with accelerator.accumulate(model):
                outputs = model(
                    input_ids=batch["input_ids"],
                    attention_mask=batch["attention_mask"],
                    labels=batch["labels"],  # Standard CE loss computed by model
                )
                loss = outputs.loss

                accelerator.backward(loss)
                if accelerator.sync_gradients:
                    accelerator.clip_grad_norm_(trainable_params, 1.0)
                optimizer.step()
                scheduler.step()
                optimizer.zero_grad()

            total_loss += loss.item()
            num_steps += 1
            if step % 20 == 0:
                accelerator.print(f"  Epoch {epoch} step {step}/{len(loader)} "
                                  f"loss={loss.item():.4f}")

        avg_loss = total_loss / max(num_steps, 1)
        accelerator.print(f"Epoch {epoch}/{args.epochs} | avg_loss={avg_loss:.4f}")

        # Validate
        if epoch % args.eval_every_n_epochs == 0:
            accelerator.wait_for_everyone()

            val_acc = 0.0
            if accelerator.is_main_process:
                accelerator.print(f"  [Eval] Starting validation...")
                val_acc = validate(model, tokenizer, val_raw, accelerator)
                accelerator.print(f"  [Eval] Epoch {epoch} | val_accuracy={val_acc:.4f}")

                if val_acc > best_val_acc:
                    best_val_acc = val_acc
                    ckpt = Path(args.output_dir) / "best"
                    unwrapped = accelerator.unwrap_model(model)
                    unwrapped.save_pretrained(str(ckpt))
                    tokenizer.save_pretrained(str(ckpt))
                    accelerator.print(f"  ✓ Saved best LoRA adapter "
                                      f"(val_acc={best_val_acc:.4f}) → {ckpt}")
                else:
                    accelerator.print(f"  No improvement (best={best_val_acc:.4f})")

            accelerator.wait_for_everyone()

    # Save final model if no eval done
    if best_val_acc == 0.0 and accelerator.is_main_process:
        ckpt = Path(args.output_dir) / "best"
        unwrapped = accelerator.unwrap_model(model)
        unwrapped.save_pretrained(str(ckpt))
        tokenizer.save_pretrained(str(ckpt))
        accelerator.print(f"  Saved final LoRA adapter → {ckpt}")

    accelerator.print(f"\nTraining complete. Best val_accuracy: {best_val_acc:.4f}")
    accelerator.print(f"Best LoRA adapter: {args.output_dir}/best")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="AgentArk Baseline — Stage 1: Standard SFT (LoRA, Uniform Loss)"
    )
    parser.add_argument("--model_name", type=str, required=True,
                        choices=["llama", "qwen"],
                        help="Base model: 'llama' (LLaMA-3.1-8B-Instruct) or 'qwen' (Qwen2.5-7B-Instruct)")
    parser.add_argument("--data_pkl", type=str, required=True,
                        help="Path to splits pkl file (from split_data.py)")
    parser.add_argument("--output_dir", type=str, required=True,
                        help="Directory to save LoRA adapter checkpoints")
    parser.add_argument("--epochs", type=int, default=3,
                        help="Number of training epochs (default: 3)")
    parser.add_argument("--batch_size", type=int, default=4,
                        help="Per-device batch size (default: 4)")
    parser.add_argument("--lr", type=float, default=2e-4,
                        help="Learning rate for LoRA (default: 2e-4)")
    parser.add_argument("--lora_r", type=int, default=32,
                        help="LoRA rank (default: 32)")
    parser.add_argument("--lora_alpha", type=int, default=64,
                        help="LoRA alpha (default: 64)")
    parser.add_argument("--eval_every_n_epochs", type=int, default=1,
                        help="Evaluate on val set every N epochs (default: 1)")
    parser.add_argument("--max_samples", type=int, default=0,
                        help="Max training samples to use. 0 = all (default: 0)")
    parser.add_argument("--grad_accum_steps", type=int, default=1,
                        help="Gradient accumulation steps (default: 1)")
    args = parser.parse_args()
    train(args)


if __name__ == "__main__":
    main()
